import { base44 } from "@/api/base44Client";
import { createAuditLog } from "@/lib/tenantNova";
import { activeOnly, agingBucket, daysSince, daysUntil, isAdminSafeDocument, isDraftLike, leaseBalance } from "@/lib/operationalReports";

export const COMMAND_WARNING = "Notifications and tasks are internal reminders only. They do not send messages, notices, legal communications, payment reminders, emails, SMS, push notifications, or collections communications.";
export const safeAdminUrl = (url) => url && url.startsWith("/admin") ? url : "";
const now = () => new Date().toISOString();
const short = (id) => id ? id.slice(0, 8) : "record";
const taskTypeFor = (eventType) => ({ Maintenance: "Maintenance Follow-Up", Arrears: "Arrears Review", Lease: "Lease Review", Document: "Document Review", Application: "Application Review", Inspection: "Inspection Review", Compliance: "Compliance Review", Forms: "Form Draft Review", InvestorReport: "Investor Report Review" }[eventType] || "Other");

function notification(org, eventType, title, message, severity, relatedType, record, url) {
  return { organization_id: org, event_type: eventType, event_title: title, event_message: message, severity, related_entity_type_nullable: relatedType, related_entity_id_nullable: record?.id || "", property_id_nullable: record?.property_id || record?.property_id_nullable || "", unit_id_nullable: record?.unit_id || record?.unit_id_nullable || "", lease_id_nullable: record?.lease_id || record?.lease_id_nullable || "", tenant_id_nullable: record?.tenant_id || "", applicant_user_id_nullable: record?.applicant_user_id || record?.applicant_user_id_nullable || "", is_read: false, action_url_nullable: safeAdminUrl(url), internal_only: true, is_active: true, created_at: now() };
}

export async function createSystemNotification(access, event) {
  const created = await base44.entities.NotificationEvent.create({ ...event, created_by_user_id_nullable: access.user?.id || "system" });
  await createAuditLog({ organizationId: access.organization.id, user: access.user, role: access.membership?.role, action: "NotificationEvent created by system trigger", entityType: "NotificationEvent", entityId: created.id, afterValues: { event_type: created.event_type, severity: created.severity }, reason: "Phase 1I dummy/test internal reminder generation only" });
  return created;
}

export async function createTaskFromNotification(access, event) {
  const task = await base44.entities.AdminTask.create({ organization_id: access.organization.id, task_type: taskTypeFor(event.event_type), title: event.event_title, description: event.event_message, priority: event.severity === "Critical" ? "Urgent" : event.severity === "Urgent" ? "High" : "Normal", status: "Open", assigned_to_user_id_nullable: event.assigned_to_user_id_nullable || "", created_by_user_id_nullable: access.user.id, related_entity_type_nullable: event.related_entity_type_nullable, related_entity_id_nullable: event.related_entity_id_nullable, property_id_nullable: event.property_id_nullable, unit_id_nullable: event.unit_id_nullable, lease_id_nullable: event.lease_id_nullable, tenant_id_nullable: event.tenant_id_nullable, applicant_user_id_nullable: event.applicant_user_id_nullable, internal_admin_note: "Created from internal NotificationEvent. No external message was sent.", is_active: true, created_at: now() });
  await createAuditLog({ organizationId: access.organization.id, user: access.user, role: access.membership?.role, action: "AdminTask created", entityType: "AdminTask", entityId: task.id, afterValues: { title: task.title, task_type: task.task_type }, reason: "Phase 1I internal task created" });
  await createAuditLog({ organizationId: access.organization.id, user: access.user, role: access.membership?.role, action: "AdminTask created from NotificationEvent", entityType: "NotificationEvent", entityId: event.id, afterValues: { task_id: task.id }, reason: "No external communication was sent" });
  return task;
}

export function filterVisibleNotifications(events, filters) {
  const nowTime = Date.now();
  return events.filter(activeOnly).filter(e => !e.dismissed_at_nullable).filter(e => filters.severity ? e.severity === filters.severity : true).filter(e => filters.event_type ? e.event_type === filters.event_type : true).filter(e => filters.property_id_nullable ? e.property_id_nullable === filters.property_id_nullable : true).filter(e => filters.assigned_to_user_id_nullable ? e.assigned_to_user_id_nullable === filters.assigned_to_user_id_nullable : true).filter(e => filters.readState === "read" ? e.is_read : filters.readState === "unread" ? !e.is_read : true).filter(e => filters.snoozedState === "snoozed" ? e.snoozed_until_nullable && new Date(e.snoozed_until_nullable).getTime() > nowTime : filters.snoozedState === "visible" ? !e.snoozed_until_nullable || new Date(e.snoozed_until_nullable).getTime() <= nowTime : true);
}

export function filterTasks(tasks, filters) {
  const today = new Date().toISOString().slice(0, 10);
  return tasks.filter(activeOnly).filter(t => filters.status ? t.status === filters.status : true).filter(t => filters.priority ? t.priority === filters.priority : true).filter(t => filters.task_type ? t.task_type === filters.task_type : true).filter(t => filters.property_id_nullable ? t.property_id_nullable === filters.property_id_nullable : true).filter(t => filters.assigned_to_user_id_nullable ? t.assigned_to_user_id_nullable === filters.assigned_to_user_id_nullable : true).filter(t => filters.due === "overdue" ? t.due_date_nullable && t.due_date_nullable < today : filters.due === "today" ? t.due_date_nullable === today : filters.due === "future" ? t.due_date_nullable && t.due_date_nullable > today : true);
}

export async function generateInternalReminders(access) {
  const org = access.organization.id;
  const [properties, units, leases, participants, ledger, documents, maintenance, inspections, applications, forms, compliance, workflows, reports, existing] = await Promise.all([base44.entities.Property.filter({ organization_id: org }), base44.entities.Unit.filter({ organization_id: org }), base44.entities.Lease.filter({ organization_id: org }), base44.entities.LeaseParticipant.filter({ organization_id: org }), base44.entities.FinancialLedgerEntry.filter({ organization_id: org }), base44.entities.Document.filter({ organization_id: org }), base44.entities.MaintenanceRequest.filter({ organization_id: org }), base44.entities.InspectionReport.filter({ organization_id: org }), base44.entities.RentalApplication.filter({ organization_id: org }), base44.entities.FormsLibrary.filter({ organization_id: org }), base44.entities.ComplianceRule.filter({ organization_id: org }), base44.entities.FormWorkflowRule.filter({ organization_id: org }), base44.entities.InvestorReport.filter({ organization_id: org }), base44.entities.NotificationEvent.filter({ organization_id: org })]);
  const proposals = [];
  maintenance.filter(activeOnly).forEach(m => { if (m.priority === "Emergency" && !["Completed", "Closed"].includes(m.status)) proposals.push(notification(org, "Maintenance", "Emergency maintenance needs review", `Maintenance request ${short(m.id)} requires urgent internal follow-up.`, "Critical", "MaintenanceRequest", m, "/admin/maintenance")); if (!["Completed", "Closed"].includes(m.status) && daysSince(m.submitted_at || m.created_date) > 7) proposals.push(notification(org, "Maintenance", "Maintenance request may be stale", `Maintenance request ${short(m.id)} is overdue for internal review.`, "Warning", "MaintenanceRequest", m, "/admin/maintenance")); if (m.status === "Reopened") proposals.push(notification(org, "Maintenance", "Maintenance request reopened", `Maintenance request ${short(m.id)} was reopened and needs admin follow-up.`, "Urgent", "MaintenanceRequest", m, "/admin/maintenance")); if (m.status === "Tenant Confirmation") proposals.push(notification(org, "Maintenance", "Maintenance awaiting confirmation", `Maintenance request ${short(m.id)} is awaiting confirmation workflow review.`, "Info", "MaintenanceRequest", m, "/admin/maintenance")); });
  leases.filter(activeOnly).forEach(l => { const entries = ledger.filter(e => e.lease_id === l.id); const bal = leaseBalance(entries); if (bal > 0) proposals.push(notification(org, "Arrears", "Lease has arrears", `Lease ${short(l.id)} has an internal arrears review reminder.`, "Urgent", "Lease", l, `/admin/ledger/lease/${l.id}`)); const oldest = entries.filter(e => e.debit_credit_type === "Debit").map(e => e.due_date_optional || e.effective_date).filter(Boolean).sort()[0]; if (bal > 0 && oldest && agingBucket(daysSince(oldest)) !== "0–7 days") proposals.push(notification(org, "Arrears", "Arrears aging review suggested", `Lease ${short(l.id)} reached the ${agingBucket(daysSince(oldest))} internal review bucket.`, "Warning", "Lease", l, `/admin/ledger/lease/${l.id}`)); if (l.end_date && [30, 60, 90].some(d => daysUntil(l.end_date) <= d && daysUntil(l.end_date) >= 0)) proposals.push(notification(org, "Lease", "Lease ending soon", `Lease ${short(l.id)} is ending soon and needs internal review.`, "Warning", "Lease", l, "/admin/tenants-leases")); if (l.lease_status === "Draft" && !participants.some(p => p.lease_id === l.id)) proposals.push(notification(org, "Lease", "Draft lease missing participant", `Draft lease ${short(l.id)} needs participant review.`, "Warning", "Lease", l, "/admin/lease-participants")); if (l.lease_status === "Draft") proposals.push(notification(org, "Lease", "Draft lease not signed placeholder", `Draft lease ${short(l.id)} has a signature-placeholder reminder for internal review.`, "Info", "Lease", l, "/admin/tenants-leases")); if (!documents.filter(activeOnly).filter(isAdminSafeDocument).some(d => d.category === "Lease" && d.lease_id_nullable === l.id)) proposals.push(notification(org, "Lease", "Lease missing required document placeholder", `Lease ${short(l.id)} needs internal required-document review.`, "Warning", "Lease", l, "/admin/documents")); });
  documents.filter(activeOnly).filter(isAdminSafeDocument).forEach(d => { if (d.expiry_date_nullable && daysUntil(d.expiry_date_nullable) >= 0 && daysUntil(d.expiry_date_nullable) <= 30) proposals.push(notification(org, "Document", "Document expiring soon", `Document ${short(d.id)} needs internal expiry review.`, "Warning", "Document", d, "/admin/documents")); if (d.expiry_date_nullable && d.expiry_date_nullable < new Date().toISOString().slice(0, 10)) proposals.push(notification(org, "Document", "Document expired", `Document ${short(d.id)} needs internal expired-document review.`, "Urgent", "Document", d, "/admin/documents")); if (d.visibility === "Admin Only" && isDraftLike(d.title)) proposals.push(notification(org, d.category === "Notice" ? "Forms" : "Document", "Admin draft awaiting review", `Admin-only draft ${short(d.id)} needs internal review.`, "Warning", "Document", d, "/admin/documents")); if (d.requires_signature && d.signature_status !== "Signed") proposals.push(notification(org, "Document", "Unsigned document placeholder", `Document ${short(d.id)} has an unsigned placeholder status.`, "Info", "Document", d, "/admin/documents")); });
  applications.filter(activeOnly).forEach(a => { if (a.application_status === "Submitted") proposals.push(notification(org, "Application", "New application submitted", `Application ${short(a.id)} needs internal review.`, "Info", "RentalApplication", a, `/admin/applications/${a.id}`)); if (a.application_status === "Under Review" && daysSince(a.submitted_at || a.created_date) > 7) proposals.push(notification(org, "Application", "Application under review too long", `Application ${short(a.id)} needs internal follow-up.`, "Warning", "RentalApplication", a, `/admin/applications/${a.id}`)); if (a.application_status === "More Info Requested") proposals.push(notification(org, "Application", "More information request pending", `Application ${short(a.id)} has a pending internal follow-up reminder.`, "Info", "RentalApplication", a, `/admin/applications/${a.id}`)); if (a.application_status === "Approved" && !a.linked_lease_id_nullable) proposals.push(notification(org, "Application", "Approved application not converted", `Application ${short(a.id)} needs lease conversion review.`, "Warning", "RentalApplication", a, `/admin/applications/${a.id}`)); });
  inspections.filter(activeOnly).forEach(i => { if (!i.shared_with_tenant) proposals.push(notification(org, "Inspection", "Inspection unshared", `Inspection ${short(i.id)} needs internal sharing-status review.`, "Info", "InspectionReport", i, "/admin/inspections")); if (!i.photos_array?.length || !i.tenant_visible_notes) proposals.push(notification(org, "Inspection", "Inspection missing photos or notes", `Inspection ${short(i.id)} needs completion review.`, "Warning", "InspectionReport", i, "/admin/inspections")); });
  compliance.filter(activeOnly).filter(r => r.verification_status !== "Verified").forEach(r => proposals.push(notification(org, "Compliance", "Compliance rule unverified", `Compliance rule ${short(r.id)} needs internal verification.`, "Warning", "ComplianceRule", r, "/admin/compliance-rules")));
  forms.filter(activeOnly).filter(f => f.verification_status !== "Verified").forEach(f => proposals.push(notification(org, "Forms", "Form library record unverified", `Form record ${short(f.id)} needs internal verification.`, "Warning", "FormsLibrary", f, "/admin/forms-library")));
  workflows.filter(activeOnly).filter(w => w.verification_status !== "Verified").forEach(w => proposals.push(notification(org, "Forms", "Form workflow unverified", `Form workflow ${short(w.id)} needs internal verification.`, "Warning", "FormWorkflowRule", w, "/admin/form-workflows")));
  reports.filter(activeOnly).forEach(r => { if (r.report_status === "Draft") proposals.push(notification(org, "InvestorReport", "Investor report draft awaiting review", `Investor report ${short(r.id)} needs internal review.`, "Info", "InvestorReport", r, `/admin/investor-reports/${r.id}`)); if (r.report_status === "Exported") proposals.push(notification(org, "InvestorReport", "Investor report exported placeholder", `Investor report ${short(r.id)} has an exported placeholder awaiting internal approval.`, "Info", "InvestorReport", r, `/admin/investor-reports/${r.id}`)); });
  const existingKeys = new Set(existing.filter(activeOnly).map(e => `${e.event_type}:${e.related_entity_type_nullable}:${e.related_entity_id_nullable}:${e.event_title}`));
  const created = [];
  for (const event of proposals) { const key = `${event.event_type}:${event.related_entity_type_nullable}:${event.related_entity_id_nullable}:${event.event_title}`; if (!existingKeys.has(key)) created.push(await createSystemNotification(access, event)); }
  return created;
}