import { base44 } from "@/api/base44Client";
import { createAuditLog } from "@/lib/tenantNova";

export const NEXT_REVIEW = "Complete GitHub/code review and database/security verification before entering real tenant data or building live integrations.";
export const activeOnly = (r) => r && !r.deleted_at && r.is_active !== false;
export const countBy = (rows, field) => rows.reduce((acc, row) => { const key = row[field] || "Unspecified"; acc[key] = (acc[key] || 0) + 1; return acc; }, {});

export const integrationSeeds = [
  ["Payments","Payment processor readiness","Track future payment processor review only.","Future online rent payment readiness.","Blocked","Critical",true,true,false,true,"Payment compliance, vendor, privacy, financial, security, and production approval required."],
  ["Banking","PAD / rent collection readiness","Track future PAD/rent collection readiness only.","Future pre-authorized debit readiness.","Blocked","Critical",true,true,false,true,"Banking and payment compliance review required."],
  ["Accounting","Accounting export readiness","Track future accounting export readiness only.","Future accounting export review.","Not Started","High",true,false,false,false,"Accounting review required before build."],
  ["Email","Email sending readiness","Track future email delivery readiness only.","Future admin-controlled email notifications.","Blocked","High",true,false,true,true,"Communication and legal notice delivery review required."],
  ["SMS","SMS sending readiness","Track future SMS delivery readiness only.","Future admin-controlled SMS notifications.","Blocked","High",true,false,true,true,"Communication consent review required."],
  ["E-Signature","E-signature readiness","Track future e-signature readiness only.","Future lease/document signature workflow.","Blocked","Critical",true,false,true,true,"Legal and vendor review required."],
  ["File Storage","Secure file storage readiness","Track secure private file storage verification.","Future production document storage hardening.","Blocked","Critical",true,false,false,true,"Private storage authorization review required."],
  ["Credit Screening","Credit/background screening readiness","Track future screening integration readiness only.","Future screening workflow review.","Blocked","Critical",true,false,false,true,"Privacy/legal/vendor review required."],
  ["Investor Portal","Investor portal readiness","Track future investor portal readiness only.","Future owner/investor read-only access review.","Not Started","High",true,false,false,false,"Investor data sharing review required."],
  ["Vendor Portal","Vendor portal readiness","Track future vendor portal readiness only.","Future vendor access review.","Not Started","High",true,false,false,false,"Vendor privacy/access review required."],
  ["Government Forms","Government/legal form delivery readiness","Track future government/legal delivery readiness only.","Future legal notice/form delivery review.","Blocked","Critical",true,false,true,true,"Legal review required. No filing/delivery is active."]
];

export const hardeningSeeds = [
  ["Database Security","Confirm database-level RLS / row-level security","Critical",true,false,false,false,"Database/security-rule evidence for every entity."], ["Database Security","Confirm organization isolation at database/security-rule level","Critical",true,false,false,false,"Evidence that organization_id isolation cannot be bypassed."], ["Authorization","Confirm tenant LeaseParticipant isolation at database/security-rule level","Critical",true,false,false,false,"Evidence direct-ID lease access is blocked."], ["Authorization","Confirm applicant isolation at database/security-rule level","Critical",true,false,false,false,"Evidence direct-ID application access is blocked."], ["Field-Level Security","Confirm field-level protection for internal notes and sensitive financial fields","Critical",true,false,false,false,"Evidence sensitive fields cannot be read by unauthorized roles."], ["File Storage","Confirm secure private file storage","Critical",true,false,false,false,"Evidence private files are not publicly accessible."], ["File Storage","Confirm signed URL / file access authorization","Critical",true,false,false,false,"Evidence signed URL access is authorized and expires."], ["Audit","Confirm AuditLog tamper resistance / immutability","Critical",true,false,false,false,"Evidence normal app users cannot edit/delete audit logs."], ["Backups","Confirm backup and restore plan","High",true,false,false,false,"Backup/restore runbook evidence."], ["Data Retention","Confirm data retention policy","High",true,false,false,false,"Retention/deletion policy evidence."], ["Privacy","Confirm privacy policy and consent language","Critical",true,false,false,false,"Legal/privacy-approved policy and consent text."], ["Legal","Confirm NS tenancy legal form/version review","Critical",false,false,false,true,"External legal review evidence."], ["Financial","Confirm financial/accounting review of ledger and reports","Critical",false,false,true,false,"Accounting review evidence."], ["Financial","Confirm payment compliance review before any rent collection","Critical",false,false,true,false,"Payment compliance evidence."], ["Communications","Confirm email/SMS/legal notice delivery review before communication integrations","Critical",false,true,false,true,"Communication consent and legal delivery review evidence."], ["Authentication","Confirm production authentication/session controls","High",true,false,false,false,"Session/auth control review evidence."], ["Authorization","Confirm role/permission matrix review","Critical",true,false,false,false,"Approved role matrix evidence."], ["Testing","Confirm test data purge plan","Critical",true,false,false,false,"Purge plan before real data."], ["Deployment","Confirm GitHub/code security review","Critical",true,false,false,false,"Code review evidence."], ["Incident Response","Confirm deployment monitoring and incident response plan","High",true,false,false,false,"Monitoring and incident response runbook."]
];

export const securitySeeds = [
  ["RLS","Verify RLS for every entity","Critical","All modules","All entity access must be verified at database/security-rule level.",true,true], ["Authorization","Verify tenant direct-ID access blocked at database/security-rule level","Critical","Tenant Portal","Direct-ID tenant access must fail for unauthorized records.",true,true], ["Authorization","Verify applicant direct-ID access blocked at database/security-rule level","Critical","Applicant Portal","Direct-ID applicant access must fail for unauthorized records.",true,true], ["Authorization","Verify admin organization isolation","Critical","Admin Portal","Admin users must not access other organizations.",true,true], ["Field Redaction","Verify internal field redaction cannot be bypassed","Critical","All modules","Internal notes and sensitive fields require field-level review.",true,true], ["File Access","Verify document/file references cannot be accessed directly","Critical","Documents","File/storage references require secure authorization review.",true,true], ["AuditLog","Verify AuditLog cannot be edited/deleted by normal app users","Critical","Audit Logs","Audit immutability requires verification.",true,true], ["Routing","Verify routes/navigation do not expose unapproved modules","High","Routing","Only approved Phase 1A–1J routes should be present.",true,false], ["API Access","Verify no real payment/email/SMS/e-signature integrations exist","Critical","Integrations","No live integrations should exist in prototype.",true,true], ["GitHub Code Review","Verify GitHub repo matches approved Phase 1A–1J scope","Critical","Codebase","External code review required before real data.",true,true], ["Secrets","Verify no hardcoded secrets/API keys","Critical","Codebase","No secrets or API keys may be hardcoded.",true,true], ["Routing","Verify test/dummy data warnings remain visible","High","Admin UI","Prototype warning banners must remain prominent.",true,false]
];

async function logCreate(access, entity, record) { await createAuditLog({ organizationId: access.organization.id, user: access.user, role: access.membership?.role, action: `${entity} created`, entityType: entity, entityId: record.id, afterValues: { title: record.title || record.integration_name }, reason: "Phase 1J dummy/test readiness checklist seed or create" }); }

export async function ensureReadinessSeedData(access) {
  const org = access.organization.id;
  const [integrations, hardening, security] = await Promise.all([base44.entities.IntegrationReadinessItem.filter({ organization_id: org }), base44.entities.ProductionHardeningItem.filter({ organization_id: org }), base44.entities.SecurityReviewItem.filter({ organization_id: org })]);
  const existingIntegration = new Set(integrations.filter(activeOnly).map(i => i.integration_name));
  for (const [category, name, description, use, status, risk, sensitive, money, legal, personal, blocker] of integrationSeeds) if (!existingIntegration.has(name)) { const item = await base44.entities.IntegrationReadinessItem.create({ organization_id: org, integration_category: category, integration_name: name, description, intended_use: use, status, risk_level: risk, handles_sensitive_data_boolean: sensitive, handles_money_boolean: money, handles_legal_notice_boolean: legal, handles_personal_information_boolean: personal, vendor_review_required_boolean: true, legal_review_required_boolean: legal, privacy_review_required_boolean: personal || sensitive, financial_review_required_boolean: money, security_review_required_boolean: true, production_approval_required_boolean: true, notes: "Prototype readiness placeholder only. No integration is active.", blocker_reason_nullable: blocker, is_active: true }); await logCreate(access, "IntegrationReadinessItem", item); }
  const existingHardening = new Set(hardening.filter(activeOnly).map(i => i.title));
  for (const [category, title, priority, realData, comms, payments, legalNotice, evidence] of hardeningSeeds) if (!existingHardening.has(title)) { const item = await base44.entities.ProductionHardeningItem.create({ organization_id: org, hardening_category: category, title, description: `${title}. Tracking only; this does not prove verification.`, status: priority === "Critical" ? "Blocked" : "Not Started", priority, blocks_real_tenant_data_boolean: realData, blocks_external_communication_boolean: comms, blocks_payment_processing_boolean: payments, blocks_legal_notice_use_boolean: legalNotice, required_evidence: evidence, evidence_notes: "", is_active: true }); await logCreate(access, "ProductionHardeningItem", item); }
  const existingSecurity = new Set(security.filter(activeOnly).map(i => i.title));
  for (const [area, title, severity, module, evidence, blocksProd, blocksData] of securitySeeds) if (!existingSecurity.has(title)) { const item = await base44.entities.SecurityReviewItem.create({ organization_id: org, review_area: area, title, description: `${title}. Tracking only; independent verification is still required.`, severity, status: "Open", affected_module: module, evidence_required: evidence, evidence_notes: "", recommended_fix: NEXT_REVIEW, blocks_production_boolean: blocksProd, blocks_real_data_boolean: blocksData, created_by_user_id_nullable: access.user.id, is_active: true }); await logCreate(access, "SecurityReviewItem", item); }
}

export function buildReadinessSummary(integrations, hardening, security) {
  const i = integrations.filter(activeOnly), h = hardening.filter(activeOnly), s = security.filter(activeOnly);
  return { integrationByStatus: countBy(i, "status"), hardeningByStatus: countBy(h, "status"), securityByStatus: countBy(s, "status"), launchBlockers: { criticalHardeningNotVerified: h.filter(x => x.priority === "Critical" && x.status !== "Verified").length, criticalSecurityOpen: s.filter(x => x.severity === "Critical" && ["Open", "In Review"].includes(x.status)).length, blockedIntegrations: i.filter(x => x.status === "Blocked").length, blocksRealTenantData: h.filter(x => x.blocks_real_tenant_data_boolean && x.status !== "Verified").length + s.filter(x => x.blocks_real_data_boolean && !["Fixed","Not Applicable"].includes(x.status)).length, blocksPayments: h.filter(x => x.blocks_payment_processing_boolean && x.status !== "Verified").length + i.filter(x => x.handles_money_boolean && !["Rejected","Archived"].includes(x.status)).length, blocksCommunications: h.filter(x => x.blocks_external_communication_boolean && x.status !== "Verified").length, blocksLegalNotices: h.filter(x => x.blocks_legal_notice_use_boolean && x.status !== "Verified").length + i.filter(x => x.handles_legal_notice_boolean && !["Rejected","Archived"].includes(x.status)).length }, safety: { realTenantData: "No", externalCommunications: "No", payments: "No", legalNotices: "No", investorSharing: "No", productionLaunch: "No" }, nextReview: NEXT_REVIEW };
}

export function canApproveIntegration(item) { return item.notes && item.notes.toLowerCase().includes("review acknowledged"); }
export function needsEvidenceStatus(status) { return ["Verified", "Fixed", "Accepted Risk"].includes(status); }