import React, { useEffect, useMemo, useState } from "react";
import { useOutletContext } from "react-router-dom";
import { base44 } from "@/api/base44Client";
import DocumentForm from "@/components/tenantnova/DocumentForm";
import DocumentList from "@/components/tenantnova/DocumentList";
import { createAuditLog } from "@/lib/tenantNova";
import { documentCategories, expiryStatus, getTenantDocumentContext, getTenantDocuments, logUnauthorizedDocumentAttempt } from "@/lib/documentCenter";

export default function Documents() {
  const access = useOutletContext();
  const [docs, setDocs] = useState([]), [leases, setLeases] = useState([]), [form, setForm] = useState({ category: "Other", visibility: "Tenant Only", signature_status: "Not Required", version: 1 });
  const [filters, setFilters] = useState({ q: "", category: "", lease: "", expiry: "" });
  async function load() { const visible = await getTenantDocuments(access); const context = await getTenantDocumentContext(access); const leaseRows = []; for (const leaseId of context.leaseIds) { const lease = await base44.entities.Lease.get(leaseId); if (lease) leaseRows.push(lease); } setDocs(visible); setLeases(leaseRows); }
  useEffect(() => { if (access.tenant) load(); }, [access]);
  async function submit(e) { e.preventDefault(); const allowedLeaseIds = leases.map(l => l.id); const leaseId = form.lease_id_nullable || ""; if (leaseId && !allowedLeaseIds.includes(leaseId)) { await logUnauthorizedDocumentAttempt(access, leaseId, "Tenant attempted document upload to unauthorized lease context"); return; } const saved = await base44.entities.Document.create({ ...form, organization_id: access.organization_id, tenant_id_nullable: access.tenant.id, lease_id_nullable: leaseId, uploaded_by_user_id: access.user.id, visibility: "Tenant Only", is_active: true }); await createAuditLog({ organizationId: access.organization_id, user: access.user, role: access.membership.role, action: "Tenant document uploaded", entityType: "Document", entityId: saved.id, afterValues: saved, reason: "Tenant uploaded dummy/test document" }); setForm({ category: "Other", visibility: "Tenant Only", signature_status: "Not Required", version: 1 }); load(); }
  const filtered = useMemo(() => docs.filter(d => (!filters.q || d.title.toLowerCase().includes(filters.q.toLowerCase())) && (!filters.category || d.category === filters.category) && (!filters.lease || d.lease_id_nullable === filters.lease) && (!filters.expiry || expiryStatus(d) === filters.expiry)), [docs, filters]);
  if (!access.tenant) return <div className="rounded-2xl border bg-white p-6">No tenant profile is linked to this account.</div>;
  return <section><h1 className="text-3xl font-bold">Documents</h1><div className="mt-4 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">Use dummy/test files only. Document file access is application-enforced until secure file storage permissions or signed URL controls are confirmed.</div><div className="mt-6"><DocumentForm form={form} setForm={setForm} onSubmit={submit} tenants={[access.tenant]} leases={leases} tenantMode /></div><div className="mt-6 grid gap-3 rounded-2xl border bg-white p-4 md:grid-cols-4"><input className="rounded-xl border p-3" placeholder="Search title" value={filters.q} onChange={e => setFilters({...filters, q: e.target.value})} /><select className="rounded-xl border p-3" value={filters.category} onChange={e => setFilters({...filters, category: e.target.value})}><option value="">All categories</option>{documentCategories.map(v => <option key={v}>{v}</option>)}</select><select className="rounded-xl border p-3" value={filters.lease} onChange={e => setFilters({...filters, lease: e.target.value})}><option value="">All leases</option>{leases.map(l => <option key={l.id} value={l.id}>{l.start_date}</option>)}</select><select className="rounded-xl border p-3" value={filters.expiry} onChange={e => setFilters({...filters, expiry: e.target.value})}><option value="">All expiry</option>{["No expiry","Current","Expiring soon","Expired"].map(v => <option key={v}>{v}</option>)}</select></div><div className="mt-6"><DocumentList documents={filtered} /></div></section>;
}