import React, { useEffect, useMemo, useState } from "react";
import { useOutletContext } from "react-router-dom";
import { base44 } from "@/api/base44Client";
import MaintenanceForm from "@/components/tenantnova/MaintenanceForm";
import MaintenanceList from "@/components/tenantnova/MaintenanceList";
import { getTenantLeases } from "@/lib/tenantNova";
import { createMaintenanceRequest, getTenantMaintenanceRequests, maintenancePriorities, maintenanceStatuses } from "@/lib/maintenance";

const blank = { category: "General", priority: "Medium", status: "Submitted", permission_to_enter: false, preferred_contact_method: "Portal", photos_array: [] };
export default function Maintenance() {
  const access = useOutletContext();
  const [requests, setRequests] = useState([]), [leases, setLeases] = useState([]), [properties, setProperties] = useState([]), [units, setUnits] = useState([]), [form, setForm] = useState(blank), [filters, setFilters] = useState({ q: "", status: "", priority: "" });
  async function load() { if (!access.tenant) return; const rows = await getTenantLeases(access.organization_id, access.tenant.id); const leaseRows = rows.map(r => r.lease); const propertyRows = await Promise.all(leaseRows.map(l => base44.entities.Property.get(l.property_id))); const unitRows = await Promise.all(leaseRows.map(l => base44.entities.Unit.get(l.unit_id))); setLeases(leaseRows); setProperties(propertyRows.filter(Boolean)); setUnits(unitRows.filter(Boolean)); setRequests(await getTenantMaintenanceRequests(access)); }
  useEffect(() => { load(); }, [access]);
  async function submit(e) { e.preventDefault(); const lease = leases.find(l => l.id === form.lease_id); if (!lease) return; await createMaintenanceRequest(access, { ...form, organization_id: access.organization_id, property_id: lease.property_id, unit_id: lease.unit_id, lease_id: lease.id, tenant_id: access.tenant.id, submitted_by_user_id: access.user.id, request_number: `MR-${Date.now()}`, status: "Submitted", vendor_name: "", scheduled_date: "", completed_date: "", tenant_visible_resolution_notes: "", admin_internal_notes: "" }); setForm(blank); load(); }
  const lookupMap = useMemo(() => ({ properties: Object.fromEntries(properties.map(p => [p.id, p])), units: Object.fromEntries(units.map(u => [u.id, u])) }), [properties, units]);
  const filtered = useMemo(() => requests.filter(r => (!filters.q || r.title.toLowerCase().includes(filters.q.toLowerCase()) || r.description.toLowerCase().includes(filters.q.toLowerCase())) && (!filters.status || r.status === filters.status) && (!filters.priority || r.priority === filters.priority)), [requests, filters]);
  if (!access.tenant) return <div className="rounded-2xl border bg-white p-6">No tenant profile is linked to this account.</div>;
  return <section><h1 className="text-3xl font-bold">Maintenance</h1><p className="mt-2 text-slate-600">Submit repairs and track updates connected only to your authorized lease.</p><div className="mt-6"><MaintenanceForm form={form} setForm={setForm} onSubmit={submit} leases={leases} properties={properties} units={units} tenantMode /></div><div className="mt-6 grid gap-3 rounded-2xl border bg-white p-4 md:grid-cols-3"><input className="rounded-xl border p-3" placeholder="Search" value={filters.q} onChange={e => setFilters({...filters, q: e.target.value})} /><select className="rounded-xl border p-3" value={filters.status} onChange={e => setFilters({...filters, status: e.target.value})}><option value="">All status</option>{maintenanceStatuses.map(v => <option key={v}>{v}</option>)}</select><select className="rounded-xl border p-3" value={filters.priority} onChange={e => setFilters({...filters, priority: e.target.value})}><option value="">All priority</option>{maintenancePriorities.map(v => <option key={v}>{v}</option>)}</select></div><div className="mt-6"><MaintenanceList requests={filtered} lookups={lookupMap} /></div></section>;
}