import React, { useEffect, useState } from "react";
import { useOutletContext } from "react-router-dom";
import MaintenanceRequestCard from "@/components/tenantnova/MaintenanceRequestCard";
import { createTenantMaintenance, listTenantMaintenance, maintenanceCategories, maintenancePriorities, tenantContext, tenantUpdateMaintenance } from "@/lib/phase1d";

const blank = { lease_id: "", category: "Other", priority: "Routine", description: "", photos_videos_text: "", access_instructions: "", preferred_access_times: "" };

export default function TenantMaintenance() {
  const access = useOutletContext();
  const [rows, setRows] = useState([]), [leases, setLeases] = useState([]), [form, setForm] = useState(blank);
  async function load() { const ctx = await tenantContext(access); setLeases(ctx.leases); setRows(await listTenantMaintenance(access)); }
  useEffect(() => { if (access.tenant) load(); }, [access]);
  async function submit(e) { e.preventDefault(); const saved = await createTenantMaintenance(access, form); if (saved) setForm(blank); load(); }
  async function confirm(r) { const rating = Number(window.prompt("Completion rating 1-5", r.tenant_feedback_rating || 5) || 5); const notes = window.prompt("Feedback notes", r.tenant_feedback_notes || "") || ""; await tenantUpdateMaintenance(access, r, { status: "Closed", closed_at: new Date().toISOString(), tenant_feedback_rating: rating, tenant_feedback_notes: notes }, "MaintenanceRequest closed"); load(); }
  async function reopen(r) { const notes = window.prompt("Why are you reopening this request?", r.tenant_feedback_notes || "") || ""; await tenantUpdateMaintenance(access, r, { status: "Reopened", tenant_feedback_notes: notes }, "MaintenanceRequest reopened"); load(); }
  if (!access.tenant) return <div className="rounded-2xl border bg-white p-6">No tenant profile is linked to this account.</div>;
  return <section><h1 className="text-3xl font-bold">Maintenance</h1><p className="mt-2 text-slate-600">Submit and track dummy/test maintenance requests for leases you can access.</p><div className="mt-6 rounded-2xl border bg-white p-5"><h2 className="font-bold">Submit maintenance request</h2><form onSubmit={submit} className="mt-4 grid gap-3 md:grid-cols-2"><select required className="rounded-xl border p-3" value={form.lease_id} onChange={e => setForm({...form, lease_id: e.target.value})}><option value="">Select lease</option>{leases.map(l => <option key={l.id} value={l.id}>{l.start_date} · {l.lease_status}</option>)}</select><select className="rounded-xl border p-3" value={form.category} onChange={e => setForm({...form, category: e.target.value})}>{maintenanceCategories.map(v => <option key={v}>{v}</option>)}</select><select className="rounded-xl border p-3" value={form.priority} onChange={e => setForm({...form, priority: e.target.value})}>{maintenancePriorities.map(v => <option key={v}>{v}</option>)}</select><input className="rounded-xl border p-3" placeholder="Preferred access times" value={form.preferred_access_times} onChange={e => setForm({...form, preferred_access_times: e.target.value})} /><textarea required className="rounded-xl border p-3 md:col-span-2" placeholder="Describe the issue" value={form.description} onChange={e => setForm({...form, description: e.target.value})} /><textarea className="rounded-xl border p-3 md:col-span-2" placeholder="Access instructions" value={form.access_instructions} onChange={e => setForm({...form, access_instructions: e.target.value})} /><input className="rounded-xl border p-3 md:col-span-2" placeholder="Dummy photo/video refs, comma-separated" value={form.photos_videos_text} onChange={e => setForm({...form, photos_videos_text: e.target.value})} /><button className="rounded-xl bg-teal-700 px-4 py-2 font-semibold text-white md:w-fit">Submit request</button></form></div><div className="mt-6 grid gap-4">{rows.map(r => <MaintenanceRequestCard key={r.id} request={r} onConfirm={confirm} onReopen={reopen} />)}{rows.length === 0 && <div className="rounded-2xl border bg-white p-8 text-center text-slate-500">No maintenance requests yet.</div>}</div></section>;
}