import React, { useEffect, useState } from "react";
import { useOutletContext } from "react-router-dom";
import { base44 } from "@/api/base44Client";
import PrototypeSafetyBanner from "@/components/tenantnova/PrototypeSafetyBanner";
import AuditActivity from "@/components/tenantnova/AuditActivity";
import { createAuditLog } from "@/lib/tenantNova";
import { activeOnly, canApproveIntegration, ensureReadinessSeedData } from "@/lib/readiness";

const blank = { integration_category: "Other", integration_name: "", description: "", intended_use: "", status: "Not Started", risk_level: "Medium", notes: "", blocker_reason_nullable: "", handles_sensitive_data_boolean: false, handles_money_boolean: false, handles_legal_notice_boolean: false, handles_personal_information_boolean: false, vendor_review_required_boolean: true, legal_review_required_boolean: false, privacy_review_required_boolean: true, financial_review_required_boolean: false, security_review_required_boolean: true, production_approval_required_boolean: true, is_active: true };
export default function AdminIntegrationReadiness() {
  const access = useOutletContext(), org = access.organization.id, canWrite = access.isAdmin;
  const [items, setItems] = useState([]), [logs, setLogs] = useState([]), [filters, setFilters] = useState({ category: "", status: "", risk: "", sensitive: "", money: "", legal: "" }), [form, setForm] = useState(blank), [initializationWarning, setInitializationWarning] = useState("");
  useEffect(() => { load(); }, [org]);
  async function load() { const seedResult = await ensureReadinessSeedData(access); setInitializationWarning(seedResult.initialized === false ? seedResult.message : ""); const [i,a] = await Promise.all([base44.entities.IntegrationReadinessItem.filter({ organization_id: org }), base44.entities.AuditLog.filter({ organization_id: org }, "-timestamp", 8)]); setItems(i); setLogs(a); }
  async function createItem(e) { e.preventDefault(); if (form.status === "Approved for Build Later" && !canApproveIntegration(form)) { alert("Add notes including 'review acknowledged' before approving for build later."); return; } await base44.functions.invoke("tenantNovaSecurityBoundary", { action: "createReadinessRecord", entity_name: "IntegrationReadinessItem", organization_id: org, payload: form }); setForm(blank); load(); }
  async function updateItem(item, patch) { const next = { ...item, ...patch }; if (patch.status === "Approved for Build Later" && !canApproveIntegration(next)) { alert("Add notes including 'review acknowledged' before approving for build later."); return; } const response = await base44.functions.invoke("tenantNovaSecurityBoundary", { action: "updateReadinessRecord", entity_name: "IntegrationReadinessItem", record_id: item.id, updates: patch }); const updated = response.data.record; setItems(prev => prev.map(x => x.id === item.id ? updated : x)); }
  const visible = items.filter(activeOnly).filter(i => filters.category ? i.integration_category === filters.category : true).filter(i => filters.status ? i.status === filters.status : true).filter(i => filters.risk ? i.risk_level === filters.risk : true).filter(i => filters.sensitive ? String(i.handles_sensitive_data_boolean) === filters.sensitive : true).filter(i => filters.money ? String(i.handles_money_boolean) === filters.money : true).filter(i => filters.legal ? String(i.handles_legal_notice_boolean) === filters.legal : true);
  return <section className="space-y-6"><Header title="Integration Readiness" /><PrototypeSafetyBanner />{initializationWarning && <div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm font-semibold text-amber-900">{initializationWarning}</div>}<Filters filters={filters} setFilters={setFilters} />{canWrite && <Form form={form} setForm={setForm} onSubmit={createItem} />}<div className="grid gap-4">{visible.map(item => <Card key={item.id} item={item} canWrite={canWrite} onUpdate={updateItem} />)}</div><AuditActivity logs={logs} title="Recent readiness audit activity" /></section>;
}
function Header({ title }) { return <div><p className="text-sm font-semibold uppercase text-teal-700">Phase 1J Readiness</p><h1 className="mt-2 text-3xl font-bold">{title}</h1><p className="mt-2 text-slate-600">Readiness tracking only. No external integration is activated.</p></div>; }
function Filters({ filters, setFilters }) { const u=(k,v)=>setFilters(p=>({...p,[k]:v})); return <div className="grid gap-3 rounded-2xl border bg-white p-4 md:grid-cols-6"><select value={filters.category} onChange={e=>u('category',e.target.value)} className="rounded-xl border p-2"><option value="">All categories</option>{["Payments","Accounting","Email","SMS","Push","E-Signature","File Storage","Government Forms","Banking","Credit Screening","Background Screening","Investor Portal","Vendor Portal","Other"].map(x=><option key={x}>{x}</option>)}</select><select value={filters.status} onChange={e=>u('status',e.target.value)} className="rounded-xl border p-2"><option value="">All status</option>{["Not Started","Researching","Planned","Blocked","Ready for Technical Review","Approved for Build Later","Rejected","Archived"].map(x=><option key={x}>{x}</option>)}</select><select value={filters.risk} onChange={e=>u('risk',e.target.value)} className="rounded-xl border p-2"><option value="">All risk</option>{["Low","Medium","High","Critical"].map(x=><option key={x}>{x}</option>)}</select><select value={filters.sensitive} onChange={e=>u('sensitive',e.target.value)} className="rounded-xl border p-2"><option value="">Sensitive?</option><option value="true">Yes</option><option value="false">No</option></select><select value={filters.money} onChange={e=>u('money',e.target.value)} className="rounded-xl border p-2"><option value="">Money?</option><option value="true">Yes</option><option value="false">No</option></select><select value={filters.legal} onChange={e=>u('legal',e.target.value)} className="rounded-xl border p-2"><option value="">Legal notice?</option><option value="true">Yes</option><option value="false">No</option></select></div>; }
function Form({ form, setForm, onSubmit }) { const u=(k,v)=>setForm(p=>({...p,[k]:v})); return <form onSubmit={onSubmit} className="rounded-2xl border bg-white p-4"><h2 className="font-bold">Create readiness item</h2><div className="mt-3 grid gap-3 md:grid-cols-4"><input required value={form.integration_name} onChange={e=>u('integration_name',e.target.value)} placeholder="Name" className="rounded-xl border p-2" /><select value={form.integration_category} onChange={e=>u('integration_category',e.target.value)} className="rounded-xl border p-2">{["Payments","Accounting","Email","SMS","Push","E-Signature","File Storage","Government Forms","Banking","Credit Screening","Background Screening","Investor Portal","Vendor Portal","Other"].map(x=><option key={x}>{x}</option>)}</select><select value={form.status} onChange={e=>u('status',e.target.value)} className="rounded-xl border p-2">{["Not Started","Researching","Planned","Blocked","Ready for Technical Review","Approved for Build Later","Rejected","Archived"].map(x=><option key={x}>{x}</option>)}</select><select value={form.risk_level} onChange={e=>u('risk_level',e.target.value)} className="rounded-xl border p-2">{["Low","Medium","High","Critical"].map(x=><option key={x}>{x}</option>)}</select></div><textarea value={form.notes} onChange={e=>u('notes',e.target.value)} placeholder="Notes / review acknowledged text" className="mt-3 min-h-20 w-full rounded-xl border p-2" /><button className="mt-3 rounded-xl bg-teal-700 px-4 py-2 text-white">Create</button></form>; }
function Card({ item, canWrite, onUpdate }) { return <article className="rounded-2xl border bg-white p-4"><div className="flex justify-between gap-3"><div><b>{item.integration_name}</b><p className="text-sm text-slate-600">{item.description}</p><p className="mt-1 text-xs text-slate-500">{item.integration_category} · {item.risk_level} · {item.status}</p></div></div><textarea disabled={!canWrite} defaultValue={item.notes || ""} onBlur={e=>canWrite&&onUpdate(item,{notes:e.target.value})} className="mt-3 min-h-16 w-full rounded-xl border p-2 text-sm" />{canWrite && <div className="mt-3 flex flex-wrap gap-2"><select value={item.status} onChange={e=>onUpdate(item,{status:e.target.value,reviewed_by_user_id_nullable:e.target.value==='Approved for Build Later'?item.reviewed_by_user_id_nullable:'',reviewed_at_nullable:e.target.value==='Approved for Build Later'?new Date().toISOString():''})} className="rounded-xl border p-2 text-sm">{["Not Started","Researching","Planned","Blocked","Ready for Technical Review","Approved for Build Later","Rejected","Archived"].map(x=><option key={x}>{x}</option>)}</select><button onClick={()=>onUpdate(item,{deleted_at:new Date().toISOString(),is_active:false,status:'Archived'})} className="rounded-xl border px-3 py-2 text-sm">Archive</button></div>}</article>; }