import React, { useEffect, useState } from "react";
import { Link, useOutletContext, useParams } from "react-router-dom";
import { base44 } from "@/api/base44Client";
import { adminUpdateApplication, applicationStatuses, archiveApplication, canAdminTransition, convertApplication, createApplicationDocument, jsonText } from "@/lib/applications";

export default function AdminApplicationDetail() {
  const access = useOutletContext(), { applicationId } = useParams();
  const [app, setApp] = useState(null), [docs, setDocs] = useState([]), [logs, setLogs] = useState([]);
  async function load() { const row = await base44.entities.RentalApplication.get(applicationId); setApp(row); const [documents, auditLogs] = await Promise.all([base44.entities.Document.filter({ organization_id: row.organization_id, application_id_nullable: row.id }, "-created_date", 50), base44.entities.AuditLog.filter({ organization_id: row.organization_id, entity_id: row.id }, "-timestamp", 50)]); setDocs(documents.filter(d => !d.deleted_at && d.is_active !== false)); setLogs(auditLogs); }
  useEffect(() => { load(); }, [applicationId]);
  if (!app) return <div className="rounded-2xl border bg-white p-8">Loading application...</div>;
  async function saveAdminFields() { const internal_notes = window.prompt("Internal notes", app.internal_notes || ""); if (internal_notes !== null) await adminUpdateApplication(access, app, { internal_notes }, "Admin added internal notes"); const score = window.prompt("Internal score", app.internal_score || ""); if (score !== null) await adminUpdateApplication(access, app, { internal_score: Number(score) || 0 }, "Admin changed internal score"); const message = window.prompt("Applicant-visible message", app.applicant_visible_message || ""); if (message !== null) await adminUpdateApplication(access, app, { applicant_visible_message: message }, "Admin added applicant-visible message"); load(); }
  async function changeStatus(target) { const updates = { application_status: target }; if (target === "Approved") updates.admin_review_notes = window.prompt("Approval review note required", app.admin_review_notes || "") || ""; if (target === "Declined") updates.decision_reason_internal = window.prompt("Internal decline reason required", app.decision_reason_internal || "") || ""; if (!canAdminTransition(app.application_status, target, updates)) return window.alert("Status change is not allowed or required notes are missing."); const now = new Date().toISOString(); if (target === "Approved") updates.approved_at_nullable = now; if (target === "Declined") updates.declined_at_nullable = now; if (target === "Under Review") updates.reviewed_at_nullable = now; await adminUpdateApplication(access, app, updates, `Admin changed status to ${target}`); load(); }
  async function linkDoc() { const title = window.prompt("Dummy/test document title"); const ref = window.prompt("Dummy/test file reference"); const visibility = window.confirm("Admin Only? OK = Admin Only, Cancel = applicant-visible") ? "Admin Only" : "Tenant Only"; if (!title || !ref) return; await createApplicationDocument(access, app, title, ref, visibility); load(); }
  async function archive() { if (!window.confirm("Archive this application?")) return; await archiveApplication(access, app); load(); }
  async function convert() { if (!window.confirm("Convert approved application to Tenant + Draft Lease?")) return; await convertApplication(access, app); load(); }
  return <section><Link to="/admin/applications" className="text-sm text-teal-700 underline">Back to Applications</Link><div className="mt-4 flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl font-bold">Application Review</h1><p className="text-slate-600">{app.applicant_first_name} {app.applicant_last_name} · {app.applicant_email}</p></div><span className="rounded-full bg-teal-100 px-3 py-1 text-sm text-teal-800">{app.application_status}</span></div><div className="mt-6 grid gap-4 lg:grid-cols-3"><div className="rounded-2xl border bg-white p-5 lg:col-span-2"><h2 className="font-bold">Application details</h2><dl className="mt-4 grid gap-3 text-sm md:grid-cols-2"><Field label="Desired move-in" value={app.desired_move_in_date} /><Field label="Property" value={app.property_id_nullable} /><Field label="Unit" value={app.unit_id_nullable} /><Field label="Phone" value={app.applicant_phone} /><Field label="Current address" value={app.current_address} /><Field label="Smoking" value={app.smoking_status} /></dl>{["previous_addresses_2_years_json","household_members_json","co_applicants_json","employment_info_json","income_info_json","references_json","pets_json","vehicles_json"].map(f => <div key={f} className="mt-4"><h3 className="text-sm font-semibold">{f.replaceAll("_", " ")}</h3><pre className="mt-2 overflow-auto rounded-xl bg-slate-50 p-3 text-xs">{jsonText(app[f])}</pre></div>)}</div><div className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Review actions</h2><button onClick={saveAdminFields} className="mt-3 w-full rounded-xl bg-slate-900 px-4 py-2 text-white">Notes / score / message</button><div className="mt-3 grid gap-2">{applicationStatuses.filter(s => s !== app.application_status).map(s => <button key={s} onClick={() => changeStatus(s)} className="rounded-xl border px-3 py-2 text-sm">Move to {s}</button>)}</div><button onClick={linkDoc} className="mt-3 w-full rounded-xl border px-4 py-2">Link dummy document</button><button disabled={app.application_status !== "Approved"} onClick={convert} className="mt-3 w-full rounded-xl bg-teal-700 px-4 py-2 text-white disabled:opacity-40">Convert to Tenant + Draft Lease</button><button onClick={archive} className="mt-3 w-full rounded-xl border px-4 py-2">Archive</button></div></div><div className="mt-6 rounded-2xl border bg-white p-5"><h2 className="font-bold">Linked dummy/test documents</h2>{docs.map(d => <p key={d.id} className="mt-2 text-sm"><b>{d.title}</b> · {d.visibility} · {d.file_url_or_storage_reference}</p>)}{docs.length === 0 && <p className="mt-2 text-sm text-slate-500">No documents linked.</p>}</div><div className="mt-6 rounded-2xl border bg-white p-5"><h2 className="font-bold">Application audit activity</h2>{logs.map(l => <div key={l.id} className="mt-3 rounded-xl bg-slate-50 p-3 text-sm"><b>{l.action}</b><p className="text-slate-500">{l.reason}</p></div>)}</div></section>;
}

function Field({ label, value }) { return <div><dt className="text-slate-500">{label}</dt><dd>{value || "—"}</dd></div>; }