import React, { useEffect, useState } from "react";
import { Link, useOutletContext, useParams } from "react-router-dom";
import { base44 } from "@/api/base44Client";
import AuditActivity from "@/components/tenantnova/AuditActivity";
import { archiveInvestorReport, createInvestorExportPlaceholder, INVESTOR_REPORT_WARNING, markInvestorReportReviewed, narrativeFields, updateInvestorReport } from "@/lib/investorReports";

export default function AdminInvestorReportDetail() {
  const access = useOutletContext();
  const { reportId } = useParams();
  const [report, setReport] = useState(null), [property, setProperty] = useState(null), [logs, setLogs] = useState([]), [form, setForm] = useState({});
  async function load() { const row = await base44.entities.InvestorReport.get(reportId); if (!row || row.organization_id !== access.organization_id) return; const [prop, audit] = await Promise.all([base44.entities.Property.get(row.property_id), base44.entities.AuditLog.filter({ organization_id: access.organization_id, entity_id: row.id }, "-timestamp", 50)]); setReport(row); setProperty(prop); setLogs(audit); const next = {}; narrativeFields.forEach(f => next[f] = row[f] || ""); setForm(next); }
  useEffect(() => { load(); }, [reportId]);
  if (!report) return <div className="rounded-2xl border bg-white p-6">Loading investor report...</div>;
  async function save() { await updateInvestorReport(access, report, form); load(); }
  async function review() { await markInvestorReportReviewed(access, report); load(); }
  async function exportPlaceholder() { await createInvestorExportPlaceholder(access, report, property); load(); }
  async function archive() { if (!window.confirm("Archive this investor report?")) return; await archiveInvestorReport(access, report); load(); }
  return <section><Link to="/admin/investor-reports" className="text-sm text-teal-700 underline">Back to Investor Reports</Link><h1 className="mt-3 text-3xl font-bold">Investor Report Detail</h1><div className="mt-4 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">{INVESTOR_REPORT_WARNING} Internal admin note is never included in export placeholder content.</div><div className="mt-6 grid gap-3 md:grid-cols-4">{["report_status","report_type","occupancy_rate","total_units","occupied_units","vacant_units","gross_rent_charged","rent_collected","rent_outstanding","arrears_amount","security_deposits_held","NOI","cash_flow_after_debt_optional"].map(k => <div key={k} className="rounded-2xl border bg-white p-4"><p className="text-xs text-slate-500">{k.replaceAll("_", " ")}</p><p className="font-bold">{report[k]}</p></div>)}</div><div className="mt-6 rounded-2xl border bg-white p-5"><h2 className="font-bold">Aggregate summaries</h2><pre className="mt-3 overflow-auto rounded-xl bg-slate-50 p-3 text-xs">{JSON.stringify({ property_snapshot_json: report.property_snapshot_json, maintenance_summary_json: report.maintenance_summary_json, leasing_summary_json: report.leasing_summary_json, inspection_summary_json: report.inspection_summary_json, application_summary_json: report.application_summary_json, forms_compliance_summary_json: report.forms_compliance_summary_json }, null, 2)}</pre></div><div className="mt-6 rounded-2xl border bg-white p-5"><h2 className="font-bold">Editable narrative fields</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{narrativeFields.map(field => <textarea key={field} className="rounded-xl border p-3" value={form[field] || ""} onChange={e => setForm({...form, [field]: e.target.value})} placeholder={field.replaceAll("_", " ")} />)}</div><button onClick={save} className="mt-4 rounded-xl bg-teal-700 px-4 py-2 text-white">Save changes</button></div><div className="mt-6 flex flex-wrap gap-2"><button onClick={review} className="rounded-xl bg-slate-900 px-4 py-2 text-white">Mark Reviewed</button><button onClick={exportPlaceholder} className="rounded-xl bg-slate-900 px-4 py-2 text-white">Generate Export Placeholder</button><button onClick={archive} className="rounded-xl border border-red-200 px-4 py-2 text-red-600">Archive</button>{report.attached_document_id_nullable && <span className="rounded-xl bg-slate-100 px-4 py-2 text-sm">Attached Document: {report.attached_document_id_nullable}</span>}</div><div className="mt-6"><AuditActivity logs={logs} /></div></section>;
}