import React, { useEffect, useMemo, useState } from "react";
import { useOutletContext } from "react-router-dom";
import { base44 } from "@/api/base44Client";
import MaintenanceRequestCard from "@/components/tenantnova/MaintenanceRequestCard";
import { activeOnly } from "@/lib/tenantNova";
import { adminUpdateMaintenance, archiveMaintenance, maintenanceCategories, maintenancePriorities, maintenanceStatuses, refsText, splitRefs } from "@/lib/phase1d";

export default function AdminMaintenance() {
  const access = useOutletContext(), org = access.organization.id;
  const [rows, setRows] = useState([]), [lookups, setLookups] = useState({ properties: {}, units: {}, logs: [] });
  const [filters, setFilters] = useState({ q: "", property: "", unit: "", lease: "", tenant: "", priority: "", category: "", status: "", date: "" });
  async function load() { const [reqs, props, units, logs] = await Promise.all([base44.entities.MaintenanceRequest.filter({ organization_id: org }, "-submitted_at", 200), base44.entities.Property.filter({ organization_id: org }), base44.entities.Unit.filter({ organization_id: org }), base44.entities.AuditLog.filter({ organization_id: org, entity_type: "MaintenanceRequest" }, "-timestamp", 50)]); setRows(reqs.filter(activeOnly).filter(r => r.is_active !== false)); setLookups({ properties: Object.fromEntries(props.filter(activeOnly).map(p => [p.id, p])), units: Object.fromEntries(units.filter(activeOnly).map(u => [u.id, u])), logs }); }
  useEffect(() => { load(); }, []);
  async function update(r) { const status = window.prompt("Status", r.status); if (status && status !== r.status) await adminUpdateMaintenance(access, r, { status, acknowledged_at: status === "Acknowledged" ? new Date().toISOString() : r.acknowledged_at, completed_at: status === "Completed" ? new Date().toISOString() : r.completed_at, closed_at: status === "Closed" ? new Date().toISOString() : r.closed_at }); const visible = window.prompt("Tenant-visible notes", r.tenant_visible_notes || ""); if (visible !== null && visible !== r.tenant_visible_notes) await adminUpdateMaintenance(access, r, { tenant_visible_notes: visible }); const internal = window.prompt("Internal notes", r.internal_notes || ""); if (internal !== null && internal !== r.internal_notes) await adminUpdateMaintenance(access, r, { internal_notes: internal }); const assigned = window.prompt("Assigned user placeholder", r.assigned_to_user_id_nullable || ""); const vendor = window.prompt("Vendor placeholder", r.vendor_id_nullable || ""); if (assigned !== null || vendor !== null) await adminUpdateMaintenance(access, r, { assigned_to_user_id_nullable: assigned || "", vendor_id_nullable: vendor || "" }); const estimate = Number(window.prompt("Cost estimate", r.cost_estimate || 0) || 0); const actual = Number(window.prompt("Actual cost", r.actual_cost || 0) || 0); const chargeback = Number(window.prompt("Chargeback amount", r.chargeback_amount || 0) || 0); await adminUpdateMaintenance(access, r, { cost_estimate: estimate, actual_cost: actual, chargeback_amount: chargeback }); const photos = window.prompt("Completion photo refs, comma-separated", refsText(r.completion_photos_array)); if (photos !== null) await adminUpdateMaintenance(access, r, { completion_photos_array: splitRefs(photos) }); load(); }
  async function archive(r) { if (!window.confirm("Archive this request?")) return; await archiveMaintenance(access, r); load(); }
  const filtered = useMemo(() => rows.filter(r => (!filters.q || r.description.toLowerCase().includes(filters.q.toLowerCase())) && (!filters.property || r.property_id === filters.property) && (!filters.unit || r.unit_id === filters.unit) && (!filters.lease || r.lease_id === filters.lease) && (!filters.tenant || r.tenant_id === filters.tenant) && (!filters.priority || r.priority === filters.priority) && (!filters.category || r.category === filters.category) && (!filters.status || r.status === filters.status) && (!filters.date || r.submitted_at?.slice(0,10) === filters.date)), [rows, filters]);
  return <section><h1 className="text-3xl font-bold">Maintenance Queue</h1><p className="mt-2 text-slate-600">Dummy/test maintenance workflow for triage, status updates, notes, costs, completion refs, and archive actions.</p><div className="mt-6 grid gap-3 rounded-2xl border bg-white p-4 md:grid-cols-4"><input className="rounded-xl border p-3" placeholder="Search description" value={filters.q} onChange={e => setFilters({...filters, q: e.target.value})} /><select className="rounded-xl border p-3" value={filters.priority} onChange={e => setFilters({...filters, priority: e.target.value})}><option value="">All priorities</option>{maintenancePriorities.map(v => <option key={v}>{v}</option>)}</select><select className="rounded-xl border p-3" value={filters.category} onChange={e => setFilters({...filters, category: e.target.value})}><option value="">All categories</option>{maintenanceCategories.map(v => <option key={v}>{v}</option>)}</select><select className="rounded-xl border p-3" value={filters.status} onChange={e => setFilters({...filters, status: e.target.value})}><option value="">All statuses</option>{maintenanceStatuses.map(v => <option key={v}>{v}</option>)}</select><input className="rounded-xl border p-3" placeholder="Property ID" value={filters.property} onChange={e => setFilters({...filters, property: e.target.value})} /><input className="rounded-xl border p-3" placeholder="Unit ID" value={filters.unit} onChange={e => setFilters({...filters, unit: e.target.value})} /><input className="rounded-xl border p-3" placeholder="Lease ID" value={filters.lease} onChange={e => setFilters({...filters, lease: e.target.value})} /><input className="rounded-xl border p-3" placeholder="Tenant ID" value={filters.tenant} onChange={e => setFilters({...filters, tenant: e.target.value})} /><input type="date" className="rounded-xl border p-3" value={filters.date} onChange={e => setFilters({...filters, date: e.target.value})} /></div><div className="mt-6 grid gap-4">{filtered.map(r => <MaintenanceRequestCard key={r.id} request={r} admin lookups={lookups} onUpdate={update} onArchive={archive} />)}{filtered.length === 0 && <div className="rounded-2xl border bg-white p-8 text-center text-slate-500">No maintenance requests found.</div>}</div><div className="mt-6 rounded-2xl border bg-white p-5"><h2 className="font-bold">Recent maintenance audit activity</h2>{lookups.logs.map(l => <div key={l.id} className="mt-3 rounded-xl bg-slate-50 p-3 text-sm"><b>{l.action}</b><p className="text-slate-500">{l.reason}</p></div>)}</div></section>;
}