import React, { useEffect, useState } from "react";
import { Link, useOutletContext } from "react-router-dom";
import { base44 } from "@/api/base44Client";
import ArrearsCollectionsTable from "@/components/tenantnova/ArrearsCollectionsTable";
import MetricCard from "@/components/tenantnova/MetricCard";
import OperationalSection from "@/components/tenantnova/OperationalSection";
import RiskFlagList from "@/components/tenantnova/RiskFlagList";
import { buildOperationalSummary, money, OPERATIONAL_WARNING, pct } from "@/lib/operationalReports";

export default function AdminOperationalDashboard() {
  const access = useOutletContext();
  const [summary, setSummary] = useState(null);
  useEffect(() => { load(); }, [access.organization.id]);
  async function load() {
    const org = access.organization.id;
    const [properties, units, tenants, leases, participants, ledger, documents, maintenance, inspections, applications, forms, compliance, workflows, investorReports] = await Promise.all([
      base44.entities.Property.filter({ organization_id: org }), base44.entities.Unit.filter({ organization_id: org }), base44.entities.Tenant.filter({ organization_id: org }), base44.entities.Lease.filter({ organization_id: org }), base44.entities.LeaseParticipant.filter({ organization_id: org }), base44.entities.FinancialLedgerEntry.filter({ organization_id: org }), base44.entities.Document.filter({ organization_id: org }), base44.entities.MaintenanceRequest.filter({ organization_id: org }), base44.entities.InspectionReport.filter({ organization_id: org }), base44.entities.RentalApplication.filter({ organization_id: org }), base44.entities.FormsLibrary.filter({ organization_id: org }), base44.entities.ComplianceRule.filter({ organization_id: org }), base44.entities.FormWorkflowRule.filter({ organization_id: org }), base44.entities.InvestorReport.filter({ organization_id: org })
    ]);
    setSummary(buildOperationalSummary({ properties, units, tenants, leases, participants, ledger, documents, maintenance, inspections, applications, forms, compliance, workflows, investorReports }));
  }
  if (!summary) return <div className="grid min-h-96 place-items-center"><div className="h-8 w-8 animate-spin rounded-full border-4 border-slate-200 border-t-teal-700" /></div>;
  const p = summary.portfolio, a = summary.arrears, v = summary.vacancy, m = summary.maintenanceSummary, i = summary.inspectionSummary, apps = summary.applicationSummary, d = summary.documentCompliance;
  return <section className="space-y-6"><div><p className="text-sm font-semibold uppercase text-teal-700">Admin Operational Reports</p><h1 className="mt-2 text-3xl font-bold">Operational Dashboard</h1><p className="mt-2 max-w-4xl text-slate-600">Internal admin-only decision dashboard using live aggregate dummy/test data. DashboardSnapshot was not created because persisted snapshots are unnecessary for this phase.</p></div><div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><b>Prototype warning:</b> {OPERATIONAL_WARNING}</div>
    <OperationalSection title="Portfolio Snapshot"><div className="grid gap-3 md:grid-cols-5"><MetricCard label="Properties" value={p.total_properties} /><MetricCard label="Units" value={p.total_units} /><MetricCard label="Occupied" value={p.occupied_units} tone="teal" /><MetricCard label="Vacant" value={p.vacant_units} tone="amber" /><MetricCard label="Occupancy" value={pct(p.occupancy_rate)} tone="teal" /><MetricCard label="Active leases" value={p.active_leases} /><MetricCard label="Draft leases" value={p.draft_leases} /><MetricCard label="Ending soon" value={p.leases_ending_soon} tone="amber" /><MetricCard label="Month-to-month" value={p.month_to_month_leases} /><MetricCard label="Fixed-term" value={p.fixed_term_leases} /></div></OperationalSection>
    <OperationalSection title="Property Performance" description="Open property-level operational summaries."><div className="grid gap-3 md:grid-cols-3">{summary.properties.map(property => <Link key={property.id} to={`/admin/operational-dashboard/property/${property.id}`} className="rounded-xl border bg-slate-50 p-4 hover:border-teal-500"><b>{property.property_name}</b><p className="text-sm text-slate-600">{property.street_address || property.city || "Property dashboard"}</p></Link>)}</div></OperationalSection>
    <OperationalSection title="Arrears & Collections" description="Internal admin-only arrears summary. No automatic notices, collections, messages, or Form D generation."><div className="mb-4 grid gap-3 md:grid-cols-4"><MetricCard label="Rent charged" value={money(a.rent_charged)} /><MetricCard label="Rent collected" value={money(a.rent_collected)} tone="teal" /><MetricCard label="Outstanding" value={money(a.outstanding_rent)} tone={a.outstanding_rent > 0 ? "red" : "slate"} /><MetricCard label="Leases with arrears" value={a.leases_with_arrears} tone="amber" /></div><div className="mb-4 grid gap-3 md:grid-cols-4">{Object.entries(a.buckets).map(([bucket, count]) => <MetricCard key={bucket} label={bucket} value={count} />)}</div><ArrearsCollectionsTable rows={a.highest} /></OperationalSection>
    <OperationalSection title="Vacancy & Lease Status"><div className="grid gap-3 md:grid-cols-4"><MetricCard label="Vacant units" value={v.vacant_units.length} tone="amber" /><MetricCard label="No active lease" value={v.units_with_no_active_lease.length} tone="amber" /><MetricCard label="Draft leases" value={v.draft_leases.length} /><MetricCard label="Ending 30 days" value={v.ending_30.length} /><MetricCard label="Ending 60 days" value={v.ending_60.length} /><MetricCard label="Ending 90 days" value={v.ending_90.length} /><MetricCard label="Missing participants" value={v.missing_participants.length} tone="amber" /><MetricCard label="Missing lease docs" value={v.missing_documents.length} tone="amber" /></div></OperationalSection>
    <OperationalSection title="Maintenance & Inspections"><div className="grid gap-3 md:grid-cols-5"><MetricCard label="Open maintenance" value={m.open} /><MetricCard label="Emergency" value={m.emergency} tone="red" /><MetricCard label="Stale/overdue" value={m.stale} tone="amber" /><MetricCard label="Completed period" value={m.completed_period} /><MetricCard label="Inspections period" value={i.completed_period} /><MetricCard label="Move-in" value={i.move_in} /><MetricCard label="Move-out" value={i.move_out} /><MetricCard label="Periodic" value={i.periodic} /><MetricCard label="Unshared" value={i.unshared} tone="amber" /><MetricCard label="Missing photos/notes" value={i.missing_photos_or_notes} tone="amber" /></div></OperationalSection>
    <OperationalSection title="Applications"><div className="grid gap-3 md:grid-cols-5">{Object.entries(apps).map(([label, value]) => <MetricCard key={label} label={label.replaceAll("_", " ")} value={value} tone={label === "approved_not_converted" ? "amber" : "slate"} />)}</div><p className="mt-3 text-sm text-slate-500">Application cards are aggregate counts only. Admin detail links remain in the Applications module.</p></OperationalSection>
    <OperationalSection title="Documents & Compliance"><div className="grid gap-3 md:grid-cols-5">{Object.entries(d).map(([label, value]) => <MetricCard key={label} label={label.replaceAll("_", " ")} value={value} tone={value > 0 ? "amber" : "slate"} />)}</div><p className="mt-3 text-sm text-amber-700">Legal notices and forms remain placeholders requiring admin/legal review. No automated legal notices are generated.</p></OperationalSection>
    <OperationalSection title="Risk Flags" description="Internal admin-only follow-up queue. No tenant/applicant exposure and no automated actions."><RiskFlagList flags={summary.risks} /></OperationalSection>
  </section>;
}