import React, { useEffect, useMemo, useState } from "react";
import { useOutletContext } from "react-router-dom";
import { base44 } from "@/api/base44Client";
import ContactMessageList from "@/components/tenantnova/ContactMessageList";
import { activeOnly } from "@/lib/tenantNova";
import { archiveContactMessage, contactCategories, contactStatuses, respondToContactMessage, updateContactMessage } from "@/lib/contactMessages";

export default function ContactMessages() {
  const access = useOutletContext(), org = access.organization.id;
  const [messages, setMessages] = useState([]), [lookups, setLookups] = useState({ tenants: [], properties: [], units: [], logs: [] });
  const [filters, setFilters] = useState({ q: "", category: "", status: "", tenant: "" });
  async function load() { const [rows, tenants, properties, units, logs] = await Promise.all([base44.entities.ContactMessage.filter({ organization_id: org }, "-created_date", 200), base44.entities.Tenant.filter({ organization_id: org }), base44.entities.Property.filter({ organization_id: org }), base44.entities.Unit.filter({ organization_id: org }), base44.entities.AuditLog.filter({ organization_id: org, entity_type: "ContactMessage" }, "-timestamp", 50)]); setMessages(rows.filter(activeOnly)); setLookups({ tenants: tenants.filter(activeOnly), properties: properties.filter(activeOnly), units: units.filter(activeOnly), logs }); }
  useEffect(() => { load(); }, []);
  async function respond(m) { const response = window.prompt("Response to tenant", m.admin_response || ""); if (!response) return; await respondToContactMessage(access, m, response); load(); }
  async function status(m) { const next = window.prompt("Status", m.status); if (!next) return; const note = window.prompt("Internal admin note", m.internal_admin_note || ""); await updateContactMessage(access, m, { status: next, internal_admin_note: note }); load(); }
  async function archive(m) { if (!window.confirm("Archive this contact message?")) return; await archiveContactMessage(access, m); load(); }
  const lookupMap = useMemo(() => ({ tenants: Object.fromEntries(lookups.tenants.map(t => [t.id, t])), properties: Object.fromEntries(lookups.properties.map(p => [p.id, p])), units: Object.fromEntries(lookups.units.map(u => [u.id, u])) }), [lookups]);
  const filtered = useMemo(() => messages.filter(m => (!filters.q || m.subject.toLowerCase().includes(filters.q.toLowerCase()) || m.body.toLowerCase().includes(filters.q.toLowerCase())) && (!filters.category || m.category === filters.category) && (!filters.status || m.status === filters.status) && (!filters.tenant || m.tenant_id === filters.tenant)), [messages, filters]);
  return <section><h1 className="text-3xl font-bold">Contact Messages</h1><p className="mt-2 text-slate-600">Review tenant questions, respond through the portal, and keep an audit trail.</p><div className="mt-6 grid gap-3 rounded-2xl border bg-white p-4 md:grid-cols-4"><input className="rounded-xl border p-3" placeholder="Search" value={filters.q} onChange={e => setFilters({...filters, q: e.target.value})} /><select className="rounded-xl border p-3" value={filters.category} onChange={e => setFilters({...filters, category: e.target.value})}><option value="">All categories</option>{contactCategories.map(v => <option key={v}>{v}</option>)}</select><select className="rounded-xl border p-3" value={filters.status} onChange={e => setFilters({...filters, status: e.target.value})}><option value="">All status</option>{contactStatuses.map(v => <option key={v}>{v}</option>)}</select><select className="rounded-xl border p-3" value={filters.tenant} onChange={e => setFilters({...filters, tenant: e.target.value})}><option value="">All tenants</option>{lookups.tenants.map(t => <option key={t.id} value={t.id}>{t.first_name} {t.last_name}</option>)}</select></div><div className="mt-6"><ContactMessageList messages={filtered} lookups={lookupMap} showInternal onRespond={respond} onStatus={status} onArchive={archive} /></div><div className="mt-6 rounded-2xl border bg-white p-5"><h2 className="font-bold">Recent contact audit activity</h2>{lookups.logs.map(l => <div key={l.id} className="mt-3 rounded-xl bg-slate-50 p-3 text-sm"><b>{l.action}</b><p className="text-slate-500">{l.reason}</p></div>)}</div></section>;
}