import React, { useEffect, useState } from "react";
import { useOutletContext } from "react-router-dom";
import { base44 } from "@/api/base44Client";
import { activeOnly, createAuditLog, softArchive } from "@/lib/tenantNova";

export default function LeaseParticipants() {
  const access = useOutletContext(), org = access.organization.id;
  const [data, setData] = useState({ leases: [], tenants: [], participants: [] });
  const [form, setForm] = useState({ lease_id: "", tenant_id: "", participant_role: "Primary Tenant", access_level: "Full Lease Access", is_financially_responsible: true, start_date: "", is_active: true });
  async function load() { const [leases, tenants, participants] = await Promise.all([base44.entities.Lease.filter({ organization_id: org }), base44.entities.Tenant.filter({ organization_id: org }), base44.entities.LeaseParticipant.filter({ organization_id: org })]); setData({ leases: leases.filter(activeOnly), tenants: tenants.filter(activeOnly), participants: participants.filter(activeOnly) }); }
  useEffect(() => { load(); }, []);
  async function add(e) { e.preventDefault(); const saved = await base44.entities.LeaseParticipant.create({ ...form, organization_id: org }); await createAuditLog({ organizationId: org, user: access.user, role: access.membership.role, action: "LeaseParticipant created", entityType: "LeaseParticipant", entityId: saved.id, afterValues: saved, reason: "Admin linked tenant to lease" }); load(); }
  const tenantName = id => { const t = data.tenants.find(x => x.id === id); return t ? `${t.first_name} ${t.last_name}` : "Unknown tenant"; };
  return <section><h1 className="text-3xl font-bold">Lease Participants</h1><p className="mt-2 text-slate-600">Tenant lease access is granted only through active LeaseParticipant records.</p><form onSubmit={add} className="mt-6 grid gap-3 rounded-2xl border bg-white p-5 lg:grid-cols-3"><select className="rounded-xl border p-3" value={form.lease_id} onChange={e => setForm({...form, lease_id: e.target.value})} required><option value="">Lease</option>{data.leases.map(l => <option key={l.id} value={l.id}>{l.lease_status} · {l.start_date} · ${l.rent_amount}</option>)}</select><select className="rounded-xl border p-3" value={form.tenant_id} onChange={e => setForm({...form, tenant_id: e.target.value})} required><option value="">Tenant</option>{data.tenants.map(t => <option key={t.id} value={t.id}>{t.first_name} {t.last_name}</option>)}</select><select className="rounded-xl border p-3" value={form.participant_role} onChange={e => setForm({...form, participant_role: e.target.value})}>{["Primary Tenant","Co-Tenant","Occupant","Guarantor","Former Tenant"].map(v => <option key={v}>{v}</option>)}</select><select className="rounded-xl border p-3" value={form.access_level} onChange={e => setForm({...form, access_level: e.target.value})}>{["Full Lease Access","Limited Occupant Access","Historical Access","No Portal Access"].map(v => <option key={v}>{v}</option>)}</select><input type="date" className="rounded-xl border p-3" value={form.start_date} onChange={e => setForm({...form, start_date: e.target.value})} /><label className="flex items-center gap-2 rounded-xl border p-3 text-sm"><input type="checkbox" checked={form.is_financially_responsible} onChange={e => setForm({...form, is_financially_responsible: e.target.checked})} /> Financially responsible</label><button className="rounded-xl bg-teal-700 px-4 py-3 font-semibold text-white lg:col-span-3">Add participant</button></form><div className="mt-6 rounded-2xl border bg-white p-5"><h2 className="font-bold">Current participants</h2>{data.participants.map(p => <div key={p.id} className="mt-3 flex flex-wrap justify-between gap-3 rounded-xl bg-slate-50 p-3 text-sm"><span><b>{tenantName(p.tenant_id)}</b> · {p.participant_role} · {p.access_level}</span><button onClick={() => softArchive("LeaseParticipant", p, access, "Admin archived lease participant").then(load)} className="text-red-600">Archive</button></div>)}{data.participants.length === 0 && <p className="mt-4 text-sm text-slate-500">No participants yet.</p>}</div></section>;
}