import React, { useEffect, useMemo, useState } from "react";
import { useOutletContext } from "react-router-dom";
import { base44 } from "@/api/base44Client";
import LifecycleForm from "@/components/tenantnova/LifecycleForm";
import LifecycleList from "@/components/tenantnova/LifecycleList";
import { activeOnly } from "@/lib/tenantNova";
import { archiveLifecycleAction, createLifecycleAction, lifecycleActionTypes, lifecycleStatuses, updateLifecycleAction } from "@/lib/leaseLifecycle";

const blank = { action_type: "Renewal Offer", status: "Draft" };
export default function LeaseLifecycle() {
  const access = useOutletContext(), org = access.organization.id;
  const [actions, setActions] = useState([]), [lookups, setLookups] = useState({ leases: [], tenants: [], properties: [], units: [], logs: [] });
  const [form, setForm] = useState(blank), [filters, setFilters] = useState({ q: "", type: "", status: "", property: "", tenant: "" });
  async function load() { const [records, leases, tenants, properties, units, logs] = await Promise.all([base44.entities.LeaseLifecycleAction.filter({ organization_id: org }, "-created_date", 200), base44.entities.Lease.filter({ organization_id: org }), base44.entities.Tenant.filter({ organization_id: org }), base44.entities.Property.filter({ organization_id: org }), base44.entities.Unit.filter({ organization_id: org }), base44.entities.AuditLog.filter({ organization_id: org, entity_type: "LeaseLifecycleAction" }, "-timestamp", 50)]); setActions(records.filter(activeOnly)); setLookups({ leases: leases.filter(activeOnly), tenants: tenants.filter(activeOnly), properties: properties.filter(activeOnly), units: units.filter(activeOnly), logs }); }
  useEffect(() => { load(); }, []);
  async function submit(e) { e.preventDefault(); const lease = lookups.leases.find(l => l.id === form.lease_id); if (!lease) return; await createLifecycleAction(access, { ...form, organization_id: org, property_id: lease.property_id, unit_id: lease.unit_id, tenant_id: form.tenant_id || lease.primary_tenant_id || "", created_by_user_id: access.user.id }); setForm(blank); load(); }
  async function edit(a) { const status = window.prompt("Status", a.status); if (!status) return; const tenantNote = window.prompt("Tenant-visible note", a.tenant_visible_note || ""); const internal = window.prompt("Internal admin note", a.admin_internal_note || ""); await updateLifecycleAction(access, a, { status, tenant_visible_note: tenantNote, admin_internal_note: internal }); load(); }
  async function archive(a) { if (!window.confirm("Archive this renewal/move-out action?")) return; await archiveLifecycleAction(access, a); load(); }
  const lookupMap = useMemo(() => ({ properties: Object.fromEntries(lookups.properties.map(p => [p.id, p])), units: Object.fromEntries(lookups.units.map(u => [u.id, u])) }), [lookups]);
  const filtered = useMemo(() => actions.filter(a => (!filters.q || a.title.toLowerCase().includes(filters.q.toLowerCase()) || (a.description || "").toLowerCase().includes(filters.q.toLowerCase())) && (!filters.type || a.action_type === filters.type) && (!filters.status || a.status === filters.status) && (!filters.property || a.property_id === filters.property) && (!filters.tenant || a.tenant_id === filters.tenant)), [actions, filters]);
  return <section><h1 className="text-3xl font-bold">Renewals & Move-Out</h1><p className="mt-2 text-slate-600">Manage renewal offers, move-out notices, inspections, and security deposit review steps.</p><div className="mt-6"><LifecycleForm form={form} setForm={setForm} onSubmit={submit} {...lookups} /></div><div className="mt-6 grid gap-3 rounded-2xl border bg-white p-4 md:grid-cols-5"><input className="rounded-xl border p-3" placeholder="Search" value={filters.q} onChange={e => setFilters({...filters, q: e.target.value})} /><select className="rounded-xl border p-3" value={filters.type} onChange={e => setFilters({...filters, type: e.target.value})}><option value="">All types</option>{lifecycleActionTypes.map(v => <option key={v}>{v}</option>)}</select><select className="rounded-xl border p-3" value={filters.status} onChange={e => setFilters({...filters, status: e.target.value})}><option value="">All status</option>{lifecycleStatuses.map(v => <option key={v}>{v}</option>)}</select><select className="rounded-xl border p-3" value={filters.property} onChange={e => setFilters({...filters, property: e.target.value})}><option value="">All properties</option>{lookups.properties.map(p => <option key={p.id} value={p.id}>{p.property_name}</option>)}</select><select className="rounded-xl border p-3" value={filters.tenant} onChange={e => setFilters({...filters, tenant: e.target.value})}><option value="">All tenants</option>{lookups.tenants.map(t => <option key={t.id} value={t.id}>{t.first_name} {t.last_name}</option>)}</select></div><div className="mt-6"><LifecycleList actions={filtered} lookups={lookupMap} showInternal onEdit={edit} onArchive={archive} /></div><div className="mt-6 rounded-2xl border bg-white p-5"><h2 className="font-bold">Recent lifecycle audit activity</h2>{lookups.logs.map(l => <div key={l.id} className="mt-3 rounded-xl bg-slate-50 p-3 text-sm"><b>{l.action}</b><p className="text-slate-500">{l.reason}</p></div>)}</div></section>;
}