import React, { useEffect, useMemo, useState } from "react";
import { useOutletContext } from "react-router-dom";
import { base44 } from "@/api/base44Client";
import MaintenanceForm from "@/components/tenantnova/MaintenanceForm";
import MaintenanceList from "@/components/tenantnova/MaintenanceList";
import { activeOnly } from "@/lib/tenantNova";
import { archiveMaintenanceRequest, createMaintenanceRequest, maintenancePriorities, maintenanceStatuses, updateMaintenanceRequest } from "@/lib/maintenance";

const blank = { category: "General", priority: "Medium", status: "Submitted", permission_to_enter: false, preferred_contact_method: "Portal", photos_array: [] };
export default function Maintenance() {
  const access = useOutletContext(), org = access.organization.id;
  const [requests, setRequests] = useState([]), [lookups, setLookups] = useState({ leases: [], properties: [], units: [], tenants: [], logs: [] });
  const [form, setForm] = useState(blank), [filters, setFilters] = useState({ q: "", status: "", priority: "", property: "", unit: "" });
  async function load() { const [records, leases, properties, units, tenants, logs] = await Promise.all([base44.entities.MaintenanceRequest.filter({ organization_id: org }, "-created_date", 200), base44.entities.Lease.filter({ organization_id: org }), base44.entities.Property.filter({ organization_id: org }), base44.entities.Unit.filter({ organization_id: org }), base44.entities.Tenant.filter({ organization_id: org }), base44.entities.AuditLog.filter({ organization_id: org, entity_type: "MaintenanceRequest" }, "-timestamp", 50)]); setRequests(records.filter(activeOnly)); setLookups({ leases: leases.filter(activeOnly), properties: properties.filter(activeOnly), units: units.filter(activeOnly), tenants: tenants.filter(activeOnly), logs }); }
  useEffect(() => { load(); }, []);
  async function submit(e) { e.preventDefault(); const lease = lookups.leases.find(l => l.id === form.lease_id); if (!lease) return; await createMaintenanceRequest(access, { ...form, organization_id: org, property_id: lease.property_id, unit_id: lease.unit_id, tenant_id: lease.primary_tenant_id || "", submitted_by_user_id: access.user.id, request_number: `MR-${Date.now()}`, status: form.status || "Submitted" }, "Admin"); setForm(blank); load(); }
  async function update(r) { const status = window.prompt("Status", r.status); if (!status) return; const vendor = window.prompt("Vendor name", r.vendor_name || ""); const scheduled = window.prompt("Scheduled date YYYY-MM-DD", r.scheduled_date || ""); const completed = window.prompt("Completed date YYYY-MM-DD", r.completed_date || ""); const resolution = window.prompt("Tenant-visible resolution notes", r.tenant_visible_resolution_notes || ""); const internal = window.prompt("Internal admin notes", r.admin_internal_notes || ""); await updateMaintenanceRequest(access, r, { status, vendor_name: vendor, scheduled_date: scheduled, completed_date: completed, tenant_visible_resolution_notes: resolution, admin_internal_notes: internal }); load(); }
  async function archive(r) { if (!window.confirm("Archive this maintenance request?")) return; await archiveMaintenanceRequest(access, r); load(); }
  const lookupMap = useMemo(() => ({ properties: Object.fromEntries(lookups.properties.map(p => [p.id, p])), units: Object.fromEntries(lookups.units.map(u => [u.id, u])) }), [lookups]);
  const filtered = useMemo(() => requests.filter(r => (!filters.q || r.title.toLowerCase().includes(filters.q.toLowerCase()) || r.description.toLowerCase().includes(filters.q.toLowerCase())) && (!filters.status || r.status === filters.status) && (!filters.priority || r.priority === filters.priority) && (!filters.property || r.property_id === filters.property) && (!filters.unit || r.unit_id === filters.unit)), [requests, filters]);
  return <section><h1 className="text-3xl font-bold">Maintenance</h1><p className="mt-2 text-slate-600">Track repair requests, status changes, scheduling, vendor notes, and tenant-visible updates.</p><div className="mt-6"><MaintenanceForm form={form} setForm={setForm} onSubmit={submit} leases={lookups.leases} properties={lookups.properties} units={lookups.units} /></div><div className="mt-6 grid gap-3 rounded-2xl border bg-white p-4 md:grid-cols-5"><input className="rounded-xl border p-3" placeholder="Search" value={filters.q} onChange={e => setFilters({...filters, q: e.target.value})} /><select className="rounded-xl border p-3" value={filters.status} onChange={e => setFilters({...filters, status: e.target.value})}><option value="">All status</option>{maintenanceStatuses.map(v => <option key={v}>{v}</option>)}</select><select className="rounded-xl border p-3" value={filters.priority} onChange={e => setFilters({...filters, priority: e.target.value})}><option value="">All priority</option>{maintenancePriorities.map(v => <option key={v}>{v}</option>)}</select><select className="rounded-xl border p-3" value={filters.property} onChange={e => setFilters({...filters, property: e.target.value})}><option value="">All properties</option>{lookups.properties.map(p => <option key={p.id} value={p.id}>{p.property_name}</option>)}</select><select className="rounded-xl border p-3" value={filters.unit} onChange={e => setFilters({...filters, unit: e.target.value})}><option value="">All units</option>{lookups.units.map(u => <option key={u.id} value={u.id}>{u.unit_number}</option>)}</select></div><div className="mt-6"><MaintenanceList requests={filtered} lookups={lookupMap} showInternal onUpdate={update} onArchive={archive} /></div><div className="mt-6 rounded-2xl border bg-white p-5"><h2 className="font-bold">Recent maintenance audit activity</h2>{lookups.logs.map(l => <div key={l.id} className="mt-3 rounded-xl bg-slate-50 p-3 text-sm"><b>{l.action}</b><p className="text-slate-500">{l.reason}</p></div>)}</div></section>;
}