import React, { useEffect, useMemo, useState } from "react";
import { useOutletContext } from "react-router-dom";
import { base44 } from "@/api/base44Client";
import NoticeForm from "@/components/tenantnova/NoticeForm";
import NoticeList from "@/components/tenantnova/NoticeList";
import { activeOnly } from "@/lib/tenantNova";
import { archiveNotice, createNotice, noticeStatuses, noticeTypes, updateNotice } from "@/lib/notices";

const blank = { notice_type: "General Notice", province: "NS", status: "Draft", delivery_method: "Portal", requires_acknowledgement: true };
export default function Notices() {
  const access = useOutletContext(), org = access.organization.id;
  const [notices, setNotices] = useState([]), [lookups, setLookups] = useState({ properties: [], units: [], leases: [], tenants: [], logs: [] });
  const [form, setForm] = useState(blank), [filters, setFilters] = useState({ q: "", type: "", status: "", property: "", tenant: "" });
  async function load() { const [records, properties, units, leases, tenants, logs] = await Promise.all([base44.entities.Notice.filter({ organization_id: org }, "-created_date", 200), base44.entities.Property.filter({ organization_id: org }), base44.entities.Unit.filter({ organization_id: org }), base44.entities.Lease.filter({ organization_id: org }), base44.entities.Tenant.filter({ organization_id: org }), base44.entities.AuditLog.filter({ organization_id: org, entity_type: "Notice" }, "-timestamp", 50)]); setNotices(records.filter(activeOnly)); setLookups({ properties: properties.filter(activeOnly), units: units.filter(activeOnly), leases: leases.filter(activeOnly), tenants: tenants.filter(activeOnly), logs }); }
  useEffect(() => { load(); }, []);
  async function submit(e) { e.preventDefault(); await createNotice(access, { ...form, organization_id: org, created_by_user_id: access.user.id }); setForm(blank); load(); }
  async function edit(n) { const status = window.prompt("Status", n.status); if (!status) return; const note = window.prompt("Tenant-visible note", n.tenant_visible_note || ""); const internal = window.prompt("Internal admin note", n.internal_admin_note || ""); await updateNotice(access, n, { status, tenant_visible_note: note, internal_admin_note: internal }); load(); }
  async function archive(n) { if (!window.confirm("Archive this notice/form?")) return; await archiveNotice(access, n); load(); }
  const lookupMap = useMemo(() => ({ properties: Object.fromEntries(lookups.properties.map(p => [p.id, p])) }), [lookups]);
  const filtered = useMemo(() => notices.filter(n => (!filters.q || n.title.toLowerCase().includes(filters.q.toLowerCase()) || n.body.toLowerCase().includes(filters.q.toLowerCase())) && (!filters.type || n.notice_type === filters.type) && (!filters.status || n.status === filters.status) && (!filters.property || n.property_id_nullable === filters.property) && (!filters.tenant || n.tenant_id_nullable === filters.tenant)), [notices, filters]);
  return <section><h1 className="text-3xl font-bold">Notices & Forms</h1><p className="mt-2 text-slate-600">Create, serve, archive, and audit tenant notices and Nova Scotia form references.</p><div className="mt-4 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">This phase tracks notice delivery and acknowledgement. It is not legal advice and file references remain dummy/test-only until secure storage is confirmed.</div><div className="mt-6"><NoticeForm form={form} setForm={setForm} onSubmit={submit} {...lookups} /></div><div className="mt-6 grid gap-3 rounded-2xl border bg-white p-4 md:grid-cols-5"><input className="rounded-xl border p-3" placeholder="Search" value={filters.q} onChange={e => setFilters({...filters, q: e.target.value})} /><select className="rounded-xl border p-3" value={filters.type} onChange={e => setFilters({...filters, type: e.target.value})}><option value="">All types</option>{noticeTypes.map(v => <option key={v}>{v}</option>)}</select><select className="rounded-xl border p-3" value={filters.status} onChange={e => setFilters({...filters, status: e.target.value})}><option value="">All status</option>{noticeStatuses.map(v => <option key={v}>{v}</option>)}</select><select className="rounded-xl border p-3" value={filters.property} onChange={e => setFilters({...filters, property: e.target.value})}><option value="">All properties</option>{lookups.properties.map(p => <option key={p.id} value={p.id}>{p.property_name}</option>)}</select><select className="rounded-xl border p-3" value={filters.tenant} onChange={e => setFilters({...filters, tenant: e.target.value})}><option value="">All tenants</option>{lookups.tenants.map(t => <option key={t.id} value={t.id}>{t.first_name} {t.last_name}</option>)}</select></div><div className="mt-6"><NoticeList notices={filtered} lookups={lookupMap} showInternal onEdit={edit} onArchive={archive} /></div><div className="mt-6 rounded-2xl border bg-white p-5"><h2 className="font-bold">Recent notice audit activity</h2>{lookups.logs.map(l => <div key={l.id} className="mt-3 rounded-xl bg-slate-50 p-3 text-sm"><b>{l.action}</b><p className="text-slate-500">{l.reason}</p></div>)}</div></section>;
}