import React, { useEffect, useMemo, useState } from "react";
import { Link, useOutletContext } from "react-router-dom";
import { base44 } from "@/api/base44Client";
import LedgerEntryForm from "@/components/tenantnova/LedgerEntryForm";
import LedgerTable from "@/components/tenantnova/LedgerTable";
import { activeOnly } from "@/lib/tenantNova";
import { calculateLeaseBalance, createLedgerEntry, reverseLedgerEntry } from "@/lib/ledger";

const blank = { lease_id: "", property_id: "", unit_id: "", tenant_id: "", entry_type: "Rent Charge", debit_credit_type: "Debit", amount: 0, effective_date: new Date().toISOString().slice(0,10), due_date_optional: "", payment_method: "Manual", status: "Posted", tenant_visible_note: "", internal_admin_note: "" };
export default function PortfolioLedger() {
  const access = useOutletContext(), org = access.organization.id;
  const [data, setData] = useState({ entries: [], leases: [], tenants: [], properties: [], units: [] });
  const [form, setForm] = useState(blank), [filters, setFilters] = useState({ q: "", type: "", status: "", property: "", unit: "", tenant: "", lease: "", from: "", to: "" });
  async function load() { const [entries, leases, tenants, properties, units] = await Promise.all([base44.entities.FinancialLedgerEntry.filter({ organization_id: org }, "-effective_date", 200), base44.entities.Lease.filter({ organization_id: org }), base44.entities.Tenant.filter({ organization_id: org }), base44.entities.Property.filter({ organization_id: org }), base44.entities.Unit.filter({ organization_id: org })]); setData({ entries: entries.filter(activeOnly), leases: leases.filter(activeOnly), tenants: tenants.filter(activeOnly), properties: properties.filter(activeOnly), units: units.filter(activeOnly) }); }
  useEffect(() => { load(); }, []);
  async function submit(e) { e.preventDefault(); await createLedgerEntry(access, form, "Admin posted ledger entry"); setForm(blank); load(); }
  async function reverse(e) { const reason = window.prompt("Reason for reversal"); if (!reason) return; await reverseLedgerEntry(access, e, reason); load(); }
  const filtered = useMemo(() => data.entries.filter(e => (!filters.type || e.entry_type === filters.type) && (!filters.status || e.status === filters.status) && (!filters.property || e.property_id === filters.property) && (!filters.unit || e.unit_id === filters.unit) && (!filters.tenant || e.tenant_id === filters.tenant) && (!filters.lease || e.lease_id === filters.lease) && (!filters.from || e.effective_date >= filters.from) && (!filters.to || e.effective_date <= filters.to) && (!filters.q || JSON.stringify(e).toLowerCase().includes(filters.q.toLowerCase()))), [data.entries, filters]);
  const balances = data.leases.map(l => ({ lease: l, balance: calculateLeaseBalance(data.entries.filter(e => e.lease_id === l.id)) }));
  return <section><h1 className="text-3xl font-bold">Portfolio Ledger</h1><div className="mt-4 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">Ledger immutability is application-enforced. Posted entries have no edit/delete UI and corrections must use reversal or adjustment entries. No payment processing is active; payment methods are manual/prototype placeholders only and no bank, PAD, credit card, Stripe, or Plaid integration is connected.</div><div className="mt-6"><LedgerEntryForm form={form} setForm={setForm} leases={data.leases} tenants={data.tenants} properties={data.properties} units={data.units} onSubmit={submit} /></div><div className="mt-6 grid gap-3 rounded-2xl border bg-white p-4 md:grid-cols-4"><input className="rounded-xl border p-3" placeholder="Search" value={filters.q} onChange={e => setFilters({...filters, q: e.target.value})} /><select className="rounded-xl border p-3" value={filters.type} onChange={e => setFilters({...filters, type: e.target.value})}><option value="">All types</option>{["Rent Charge","Payment","Security Deposit","Late Fee","Adjustment","Refund","NSF Fee","Damage Charge","Other"].map(v => <option key={v}>{v}</option>)}</select><select className="rounded-xl border p-3" value={filters.status} onChange={e => setFilters({...filters, status: e.target.value})}><option value="">All statuses</option>{["Pending","Posted","Failed","Reversed","Refunded"].map(v => <option key={v}>{v}</option>)}</select><select className="rounded-xl border p-3" value={filters.lease} onChange={e => setFilters({...filters, lease: e.target.value})}><option value="">All leases</option>{data.leases.map(l => <option key={l.id} value={l.id}>{l.start_date} · ${l.rent_amount}</option>)}</select><input type="date" className="rounded-xl border p-3" value={filters.from} onChange={e => setFilters({...filters, from: e.target.value})} /><input type="date" className="rounded-xl border p-3" value={filters.to} onChange={e => setFilters({...filters, to: e.target.value})} /></div><div className="mt-6"><LedgerTable entries={filtered} showInternal onReverse={reverse} /></div><div className="mt-8 rounded-2xl border bg-white p-5"><h2 className="font-bold">Calculated balances by lease</h2>{balances.map(({lease, balance}) => <Link key={lease.id} to={`/admin/ledger/lease/${lease.id}`} className="mt-3 flex justify-between rounded-xl bg-slate-50 p-3 text-sm"><span>{lease.lease_status} · {lease.start_date}</span><b>${balance.toFixed(2)}</b></Link>)}</div></section>;
}