import React, { useEffect, useState } from "react";
import { useOutletContext } from "react-router-dom";
import { base44 } from "@/api/base44Client";
import { activeOnly, createAuditLog, softArchive } from "@/lib/tenantNova";

export default function PropertiesUnits() {
  const access = useOutletContext();
  const [properties, setProperties] = useState([]), [units, setUnits] = useState([]);
  const [property, setProperty] = useState({ property_name: "", street_address: "", city: "", province: "NS", property_type: "Residential", active_status: "Active" });
  const [unit, setUnit] = useState({ property_id: "", unit_number: "", bedrooms: 1, bathrooms: 1, current_market_rent: 0, current_status: "Vacant" });
  const org = access.organization.id;
  async function load() { const [p, u] = await Promise.all([base44.entities.Property.filter({ organization_id: org }), base44.entities.Unit.filter({ organization_id: org })]); setProperties(p.filter(activeOnly)); setUnits(u.filter(activeOnly)); }
  useEffect(() => { load(); }, []);
  async function addProperty(e) { e.preventDefault(); const saved = await base44.entities.Property.create({ ...property, organization_id: org }); await createAuditLog({ organizationId: org, user: access.user, role: access.membership.role, action: "Property created", entityType: "Property", entityId: saved.id, afterValues: saved, reason: "Admin created property" }); setProperty({ ...property, property_name: "", street_address: "", city: "" }); load(); }
  async function addUnit(e) { e.preventDefault(); const saved = await base44.entities.Unit.create({ ...unit, organization_id: org }); await createAuditLog({ organizationId: org, user: access.user, role: access.membership.role, action: "Unit created", entityType: "Unit", entityId: saved.id, afterValues: saved, reason: "Admin created unit" }); setUnit({ ...unit, unit_number: "", current_market_rent: 0 }); load(); }
  return <section><h1 className="text-3xl font-bold">Properties & Units</h1><div className="mt-6 grid gap-6 lg:grid-cols-2"><form onSubmit={addProperty} className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Add Property</h2>{["property_name","street_address","city","province","property_type"].map(f => <input key={f} className="mt-3 w-full rounded-xl border p-3" value={property[f] || ""} onChange={e => setProperty({...property, [f]: e.target.value})} placeholder={f.replaceAll("_", " ")} />)}<button className="mt-3 rounded-xl bg-teal-700 px-4 py-2 text-white">Create property</button></form><form onSubmit={addUnit} className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Add Unit</h2><select className="mt-3 w-full rounded-xl border p-3" value={unit.property_id} onChange={e => setUnit({...unit, property_id: e.target.value})} required><option value="">Select property</option>{properties.map(p => <option key={p.id} value={p.id}>{p.property_name}</option>)}</select>{["unit_number","bedrooms","bathrooms","current_market_rent"].map(f => <input key={f} className="mt-3 w-full rounded-xl border p-3" value={unit[f] || ""} onChange={e => setUnit({...unit, [f]: ["bedrooms","bathrooms","current_market_rent"].includes(f) ? Number(e.target.value) : e.target.value})} placeholder={f.replaceAll("_", " ")} />)}<button className="mt-3 rounded-xl bg-teal-700 px-4 py-2 text-white">Create unit</button></form></div><div className="mt-8 grid gap-4">{properties.map(p => <div key={p.id} className="rounded-2xl border bg-white p-5"><div className="flex justify-between gap-4"><div><h3 className="font-bold">{p.property_name}</h3><p className="text-sm text-slate-500">{p.street_address}, {p.city}, {p.province}</p></div><button onClick={() => softArchive("Property", p, access, "Admin archived property").then(load)} className="text-sm text-red-600">Archive</button></div><div className="mt-4 grid gap-2 md:grid-cols-3">{units.filter(u => u.property_id === p.id).map(u => <div key={u.id} className="rounded-xl bg-slate-50 p-3 text-sm"><b>Unit {u.unit_number}</b><p>{u.current_status} · ${u.current_market_rent || 0}</p></div>)}</div></div>)}</div></section>;
}