import React, { useEffect, useState } from "react";
import { useOutletContext } from "react-router-dom";
import { base44 } from "@/api/base44Client";
import { activeOnly, createAuditLog, softArchive } from "@/lib/tenantNova";

export default function TenantsLeases() {
  const access = useOutletContext(), org = access.organization.id;
  const [data, setData] = useState({ tenants: [], properties: [], units: [], leases: [] });
  const [tenant, setTenant] = useState({ first_name: "", last_name: "", email: "", phone: "", auth_user_id: "", onboarding_status: "Not Started", active_status: "Active" });
  const [lease, setLease] = useState({ property_id: "", unit_id: "", primary_tenant_id: "", lease_type: "Fixed Term", province: "NS", start_date: "", end_date: "", rent_amount: 0, rent_due_day: 1, payment_frequency: "Monthly", lease_status: "Draft" });
  async function load() { const [tenants, properties, units, leases] = await Promise.all([base44.entities.Tenant.filter({ organization_id: org }), base44.entities.Property.filter({ organization_id: org }), base44.entities.Unit.filter({ organization_id: org }), base44.entities.Lease.filter({ organization_id: org })]); setData({ tenants: tenants.filter(activeOnly), properties: properties.filter(activeOnly), units: units.filter(activeOnly), leases: leases.filter(activeOnly) }); }
  useEffect(() => { load(); }, []);
  async function addTenant(e) { e.preventDefault(); const saved = await base44.entities.Tenant.create({ ...tenant, organization_id: org }); await createAuditLog({ organizationId: org, user: access.user, role: access.membership.role, action: "Tenant created", entityType: "Tenant", entityId: saved.id, afterValues: saved, reason: "Admin created tenant" }); setTenant({ ...tenant, first_name: "", last_name: "", email: "", phone: "", auth_user_id: "" }); load(); }
  async function addLease(e) { e.preventDefault(); const saved = await base44.entities.Lease.create({ ...lease, organization_id: org }); await createAuditLog({ organizationId: org, user: access.user, role: access.membership.role, action: "Lease created", entityType: "Lease", entityId: saved.id, afterValues: saved, reason: "Admin created lease" }); load(); }
  return <section><h1 className="text-3xl font-bold">Tenants & Leases</h1><div className="mt-6 grid gap-6 lg:grid-cols-2"><form onSubmit={addTenant} className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Add Tenant</h2>{["first_name","last_name","email","phone","auth_user_id"].map(f => <input key={f} className="mt-3 w-full rounded-xl border p-3" value={tenant[f] || ""} onChange={e => setTenant({...tenant, [f]: e.target.value})} placeholder={f === "auth_user_id" ? "Base44 user ID for portal access" : f.replaceAll("_", " ")} />)}<button className="mt-3 rounded-xl bg-teal-700 px-4 py-2 text-white">Create tenant</button></form><form onSubmit={addLease} className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Create Lease</h2><select className="mt-3 w-full rounded-xl border p-3" value={lease.property_id} onChange={e => setLease({...lease, property_id: e.target.value, unit_id: ""})} required><option value="">Property</option>{data.properties.map(p => <option key={p.id} value={p.id}>{p.property_name}</option>)}</select><select className="mt-3 w-full rounded-xl border p-3" value={lease.unit_id} onChange={e => setLease({...lease, unit_id: e.target.value})} required><option value="">Unit</option>{data.units.filter(u => !lease.property_id || u.property_id === lease.property_id).map(u => <option key={u.id} value={u.id}>Unit {u.unit_number}</option>)}</select><select className="mt-3 w-full rounded-xl border p-3" value={lease.primary_tenant_id} onChange={e => setLease({...lease, primary_tenant_id: e.target.value})}><option value="">Primary tenant convenience field</option>{data.tenants.map(t => <option key={t.id} value={t.id}>{t.first_name} {t.last_name}</option>)}</select>{["start_date","end_date","rent_amount"].map(f => <input key={f} type={f.includes("date") ? "date" : "number"} className="mt-3 w-full rounded-xl border p-3" value={lease[f] || ""} onChange={e => setLease({...lease, [f]: f === "rent_amount" ? Number(e.target.value) : e.target.value})} placeholder={f.replaceAll("_", " ")} />)}<button className="mt-3 rounded-xl bg-teal-700 px-4 py-2 text-white">Create lease</button></form></div><div className="mt-8 grid gap-4 lg:grid-cols-2"><List title="Tenants" items={data.tenants} render={t => `${t.first_name} ${t.last_name} · ${t.email}`} archive={r => softArchive("Tenant", r, access, "Admin archived tenant").then(load)} /><List title="Leases" items={data.leases} render={l => `${l.lease_status} · ${l.lease_type} · $${l.rent_amount}`} archive={r => softArchive("Lease", r, access, "Admin archived lease").then(load)} /></div></section>;
}
function List({ title, items, render, archive }) { return <div className="rounded-2xl border bg-white p-5"><h2 className="font-bold">{title}</h2>{items.map(item => <div key={item.id} className="mt-3 flex justify-between rounded-xl bg-slate-50 p-3 text-sm"><span>{render(item)}</span><button onClick={() => archive(item)} className="text-red-600">Archive</button></div>)}{items.length === 0 && <p className="mt-4 text-sm text-slate-500">No records yet.</p>}</div>; }